### ISSUE TITLE
Scheduler Hang issue

### ISSUE THREAD

**Issue by yx1215** [awslabs/autogluon#1014]
When running the examples [here ](https://auto.gluon.ai/stable/api/autogluon.core.scheduler.html) with python version 3.8.3, the process hangs. I have no ideas what caused this issue because it also happens when I was trying to test my forecasting code in python version >= 3.8.

The following is the script:
```
import numpy as np
import autogluon.core as ag

@ag.args(
        lr=ag.space.Real(1e-3, 1e-2, log=True),
        wd=ag.space.Real(1e-3, 1e-2),
        epochs=10)
def train_fn(args, reporter):
    print('lr: {}, wd: {}'.format(args.lr, args.wd))
    for e in range(args.epochs):
        dummy_accuracy = 1 - np.power(1.8, -np.random.uniform(e, 2*e))
        reporter(epoch=e+1, accuracy=dummy_accuracy, lr=args.lr, wd=args.wd)


scheduler = ag.scheduler.FIFOScheduler(
                        train_fn,
                        resource={'num_cpus': -1, 'num_gpus': 0},
                        num_trials=100,
                        reward_attr='accuracy',
                        time_attr='epoch',)
scheduler.run()
scheduler.join_jobs()
scheduler.get_training_curves(plot=True)
```

The following is the result before hanging:
```
100%|██████████| 100/100 [00:58<00:00,  1.72it/s]
100%|██████████| 100/100 [00:56<00:00,  1.76it/s]
100%|██████████| 100/100 [00:57<00:00,  1.73it/s]
100%|██████████| 100/100 [00:58<00:00,  1.71it/s]
100%|██████████| 100/100 [01:02<00:00,  1.60it/s]
100%|██████████| 100/100 [01:01<00:00,  1.62it/s]
100%|██████████| 100/100 [01:01<00:00,  1.63it/s]
100%|██████████| 100/100 [01:00<00:00,  1.66it/s]
100%|██████████| 100/100 [01:02<00:00,  1.61it/s]
```

The following is the message after I manually kill the process:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
      File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
exitcode = _main(fd, parent_sentinel)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    prepare(preparation_data)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
      File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
exitcode = _main(fd, parent_sentinel)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
--- Logging error ---
    main_content = runpy.run_path(main_path,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 265, in run_path
    main_content = runpy.run_path(main_path,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 265, in run_path
    prepare(preparation_data)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    main_content = runpy.run_path(main_path,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 265, in run_path
        return _run_module_code(code, init_globals, run_name,return _run_module_code(code, init_globals, run_name,

  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 97, in _run_module_code
    exitcode = _main(fd, parent_sentinel)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _run_code(code, mod_globals, init_globals,  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    return _run_module_code(code, init_globals, run_name,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 97, in _run_module_code

  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 87, in _run_code
    prepare(preparation_data)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    exitcode = _main(fd, parent_sentinel)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    exec(code, run_globals)
  File "/Users/yixiaxia/Desktop/亚马逊工作/autogluon/examples/forecasting/autogluon_with_3.8.py", line 22, in <module>
    _fixup_main_from_path(data['init_main_from_path'])
      File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
_run_code(code, mod_globals, init_globals,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 87, in _run_code
    main_content = runpy.run_path(main_path,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 265, in run_path
    prepare(preparation_data)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    exec(code, run_globals)
  File "/Users/yixiaxia/Desktop/亚马逊工作/autogluon/examples/forecasting/autogluon_with_3.8.py", line 22, in <module>
    main_content = runpy.run_path(main_path,    
scheduler.join_jobs()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 265, in run_path
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 122, in join_jobs
    return _run_module_code(code, init_globals, run_name,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 97, in _run_module_code
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
        _run_code(code, mod_globals, init_globals,return _run_module_code(code, init_globals, run_name,

  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 87, in _run_code
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 97, in _run_module_code
    scheduler.join_jobs()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 122, in join_jobs
    self._cleaning_tasks()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 107, in _cleaning_tasks
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    main_content = runpy.run_path(main_path,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 265, in run_path
    _run_code(code, mod_globals, init_globals,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 87, in _run_code
    self._cleaning_tasks()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 107, in _cleaning_tasks
    exec(code, run_globals)
  File "/Users/yixiaxia/Desktop/亚马逊工作/autogluon/examples/forecasting/autogluon_with_3.8.py", line 22, in <module>
    return _run_module_code(code, init_globals, run_name,    
self._clean_task_internal(task_dict)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/fifo.py", line 376, in _clean_task_internal
    self._clean_task_internal(task_dict)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/fifo.py", line 376, in _clean_task_internal
    exitcode = _main(fd, parent_sentinel)
    scheduler.join_jobs()  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    _run_code(code, mod_globals, init_globals,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/yixiaxia/Desktop/亚马逊工作/autogluon/examples/forecasting/autogluon_with_3.8.py", line 22, in <module>
    prepare(preparation_data)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    exec(code, run_globals)
  File "/Users/yixiaxia/Desktop/亚马逊工作/autogluon/examples/forecasting/autogluon_with_3.8.py", line 22, in <module>
    prepare(preparation_data)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    scheduler.join_jobs()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 122, in join_jobs
    scheduler.join_jobs()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 122, in join_jobs
    self._cleaning_tasks()
    _fixup_main_from_path(data['init_main_from_path'])  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 107, in _cleaning_tasks

  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    task_dict['ReporterThread'].join()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1011, in join
    _fixup_main_from_path(data['init_main_from_path'])    
self._cleaning_tasks()    
self._clean_task_internal(task_dict)      File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path

task_dict['ReporterThread'].join()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 107, in _cleaning_tasks
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/fifo.py", line 376, in _clean_task_internal
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1011, in join
    main_content = runpy.run_path(main_path,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 265, in run_path
    task_dict['ReporterThread'].join()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1011, in join
    self._clean_task_internal(task_dict)
    return _run_module_code(code, init_globals, run_name,  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/fifo.py", line 376, in _clean_task_internal

  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 97, in _run_module_code
    main_content = runpy.run_path(main_path,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 265, in run_path
    _run_code(code, mod_globals, init_globals,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 87, in _run_code
    self._wait_for_tstate_lock()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    exec(code, run_globals)
  File "/Users/yixiaxia/Desktop/亚马逊工作/autogluon/examples/forecasting/autogluon_with_3.8.py", line 22, in <module>
    return _run_module_code(code, init_globals, run_name,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 97, in _run_module_code
    scheduler.join_jobs()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 122, in join_jobs
    task_dict['ReporterThread'].join()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1011, in join
    _run_code(code, mod_globals, init_globals,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 87, in _run_code
    self._cleaning_tasks()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 107, in _cleaning_tasks
    self._wait_for_tstate_lock()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    exec(code, run_globals)
  File "/Users/yixiaxia/Desktop/亚马逊工作/autogluon/examples/forecasting/autogluon_with_3.8.py", line 22, in <module>
    self._clean_task_internal(task_dict)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/fifo.py", line 376, in _clean_task_internal
    scheduler.join_jobs()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 122, in join_jobs
        elif lock.acquire(block, timeout):self._cleaning_tasks()

  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 107, in _cleaning_tasks
KeyboardInterrupt
    task_dict['ReporterThread'].join()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    self._wait_for_tstate_lock()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
    self._clean_task_internal(task_dict)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/fifo.py", line 376, in _clean_task_internal
    _run_code(code, mod_globals, init_globals,
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/yixiaxia/Desktop/亚马逊工作/autogluon/examples/forecasting/autogluon_with_3.8.py", line 22, in <module>
    elif lock.acquire(block, timeout):
KeyboardInterrupt
    self._wait_for_tstate_lock()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    scheduler.join_jobs()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 122, in join_jobs
    task_dict['ReporterThread'].join()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1011, in join
    elif lock.acquire(block, timeout):
KeyboardInterrupt
    self._cleaning_tasks()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 107, in _cleaning_tasks

  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 122, in join_jobs
    elif lock.acquire(block, timeout):
KeyboardInterrupt
    self._cleaning_tasks()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 107, in _cleaning_tasks
    self._wait_for_tstate_lock()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    self._clean_task_internal(task_dict)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/fifo.py", line 376, in _clean_task_internal
    task_dict['ReporterThread'].join()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1011, in join
    elif lock.acquire(block, timeout):
KeyboardInterrupt
        self._wait_for_tstate_lock()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
self._clean_task_internal(task_dict)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/fifo.py", line 376, in _clean_task_internal
    task_dict['ReporterThread'].join()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1011, in join
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
    self._wait_for_tstate_lock()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 125, in join_jobs
    task_dict['Job'].result(timeout=timeout)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/distributed/client.py", line 219, in result
    result = self.client.sync(self._result, callback_timeout=timeout, raiseit=False)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/distributed/client.py", line 837, in sync
    return sync(
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/distributed/utils.py", line 348, in sync
    e.wait(10)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
    elif lock.acquire(block, timeout):
KeyboardInterrupt
  File "/Users/yixiaxia/Desktop/亚马逊工作/autogluon/examples/forecasting/autogluon_with_3.8.py", line 22, in <module>
    scheduler.join_jobs()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 129, in join_jobs
    logger.error("Unexpected error:", sys.exc_info()[0])
Message: 'Unexpected error:'
Arguments: (<class 'KeyboardInterrupt'>,)
Traceback (most recent call last):
  File "/Users/yixiaxia/Desktop/亚马逊工作/autogluon/examples/forecasting/autogluon_with_3.8.py", line 22, in <module>
    scheduler.join_jobs()
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/autogluon/core/scheduler/scheduler.py", line 125, in join_jobs
    task_dict['Job'].result(timeout=timeout)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/distributed/client.py", line 219, in result
    result = self.client.sync(self._result, callback_timeout=timeout, raiseit=False)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/distributed/client.py", line 837, in sync
    return sync(
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/site-packages/distributed/utils.py", line 348, in sync
    e.wait(10)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/yixiaxia/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
```

The following are the package versions that I used:
```
f8ffc22b2d38:autogluon yixiaxia$ pip list
Package               Version        Location                                               
--------------------- -------------- -------------------------------------------------------
appnope               0.1.2          
argon2-cffi           20.1.0         
async-generator       1.10           
attrs                 20.3.0         
autogluon.core        0.1.1b20210314 
autogluon.forecasting 0.1.1b20210315 /Users/yixiaxia/Desktop/亚马逊工作/autogluon/foring/src
autograd              1.3            
backcall              0.2.0          
bcrypt                3.2.0          
bleach                3.3.0          
boto3                 1.17.27        
botocore              1.20.27        
certifi               2020.12.5      
cffi                  1.14.5         
chardet               4.0.0          
click                 7.1.2          
cloudpickle           1.6.0          
ConfigSpace           0.4.18         
convertdate           2.3.2          
cryptography          3.4.6          
cycler                0.10.0         
Cython                0.29.22        
dask                  2021.3.0       
decorator             4.4.2          
defusedxml            0.7.1          
dill                  0.3.3          
distributed           2021.3.0       
entrypoints           0.3            
future                0.18.2         
gluonts               0.6.7          
graphviz              0.8.4          
HeapDict              1.0.1          
hijri-converter       2.1.1          
holidays              0.10.5.2       
idna                  2.10           
iniconfig             1.1.1          
ipykernel             5.5.0          
ipython               7.21.0         
ipython-genutils      0.2.0          
ipywidgets            7.6.3          
jedi                  0.18.0         
Jinja2                2.11.3         
jmespath              0.10.0         
joblib                1.0.1          
jsonschema            3.2.0          
jupyter               1.0.0          
jupyter-client        6.1.12         
jupyter-console       6.2.0          
jupyter-core          4.7.1          
jupyterlab-pygments   0.1.2          
jupyterlab-widgets    1.0.0          
kiwisolver            1.3.1          
korean-lunar-calendar 0.2.1          
lightgbm              3.1.1          
MarkupSafe            1.1.1          
matplotlib            3.3.4          
mistune               0.8.4          
msgpack               1.0.2          
mxnet                 1.6.0          
nbclient              0.5.3          
nbconvert             6.0.7          
nbformat              5.1.2          
nest-asyncio          1.5.1          
networkx              2.5            
notebook              6.2.0          
numpy                 1.19.5         
packaging             20.9           
pandas                1.2.3          
pandocfilters         1.4.3          
paramiko              2.7.2          
parso                 0.8.1          
pexpect               4.8.0          
pickleshare           0.7.5          
Pillow                8.1.2          
pip                   19.2.3         
pluggy                0.13.1         
prometheus-client     0.9.0          
prompt-toolkit        3.0.17         
psutil                5.7.0          
ptyprocess            0.7.0          
py                    1.10.0         
pycparser             2.20           
pydantic              1.6.1          
Pygments              2.8.1          
PyMeeus               0.5.10         
PyNaCl                1.4.0          
pyparsing             2.4.7          
pyrsistent            0.17.3         
pytest                6.2.2          
python-dateutil       2.8.1          
pytz                  2021.1         
PyYAML                5.4.1          
pyzmq                 22.0.3         
qtconsole             5.0.2          
QtPy                  1.9.0          
requests              2.25.1         
s3transfer            0.3.4          
scikit-learn          0.24.1         
scipy                 1.5.4          
Send2Trash            1.5.0          
setuptools            41.2.0         
six                   1.15.0         
sortedcontainers      2.3.0          
tblib                 1.7.0          
terminado             0.9.2          
testpath              0.4.4          
threadpoolctl         2.1.0          
toml                  0.10.2         
toolz                 0.11.1         
tornado               6.1            
tqdm                  4.59.0         
traitlets             5.0.5          
ujson                 1.35           
urllib3               1.26.3         
wcwidth               0.2.5          
webencodings          0.5.1          
wheel                 0.36.2         
widgetsnbextension    3.5.1          
xgboost               1.3.3          
zict                  2.0.0          
```

**Comment by Innixma** [comment]
What OS are you running? Are you running the script from terminal?

**Comment by Innixma** [comment]
Likely cause: On MacOS Python 3.8 defaults to `spawn` when forking instead of `fork`, which was changed from Python 3.7

https://discuss.python.org/t/multiprocessing-spawn-default-on-macos-since-python-3-8-is-slower-than-fork-method/5910

**Comment by yx1215** [comment]
> A couple questions:
> 
> 1. What OS are you running?
> 2. Are you running the script from terminal?
> 3. Have you tested other python versions?

1. I am using MacOS
2. I am running the script using Pycharm.
3. I tested both 3.8.1 and 3.8.3 and it seems that both of them have the error, while the simple script is totally fine with version 3.7.x.
