### ISSUE TITLE
Confusing error message: HPO on Random Forest

### ISSUE THREAD

**Issue by jmrichardson** [awslabs/autogluon#1031]
Hi,

When tuning RF with the following:

```
    rf_options = {
        'max_depth': ag.space.Int(5, 15),
    }
```

I get the following error:

```
Hyperparameter tuning model: RandomForest_BAG_L1 ...
Warning: Exception caused RandomForest_BAG_L1 to fail during hyperparameter tuning... Skipping this model.
Traceback (most recent call last):
  File "D:\Projects\tactory\autogluon\tabular\trainer\abstract_trainer.py", line 1075, in _train_single_full
    hpo_models, hpo_model_performances, hpo_results = model.hyperparameter_tune(X=X, y=y, k_fold=k_fold, scheduler_options=hyperparameter_tune_kwargs, **model_fit_kwargs)
  File "D:\Projects\tactory\autogluon\core\models\abstract\abstract_model.py", line 683, in hyperparameter_tune
    return self._hyperparameter_tune(scheduler_options=scheduler_options, **kwargs)
  File "D:\Projects\tactory\autogluon\core\models\ensemble\stacker_ensemble_model.py", line 166, in _hyperparameter_tune
    return super()._hyperparameter_tune(X=X, y=y, k_fold=k_fold, scheduler_options=scheduler_options, preprocess_kwargs=preprocess_kwargs, **kwargs)
  File "D:\Projects\tactory\autogluon\core\models\ensemble\bagged_ensemble_model.py", line 640, in _hyperparameter_tune
    hpo_models, hpo_model_performances, hpo_results = self.model_base.hyperparameter_tune(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, scheduler_options=scheduler_options, **kwargs)
  File "D:\Projects\tactory\autogluon\core\models\abstract\abstract_model.py", line 683, in hyperparameter_tune
    return self._hyperparameter_tune(scheduler_options=scheduler_options, **kwargs)
  File "D:\Projects\tactory\autogluon\tabular\models\rf\rf_model.py", line 166, in _hyperparameter_tune
    return skip_hpo(self, **kwargs)
  File "D:\Projects\tactory\autogluon\core\models\abstract\model_trial.py", line 90, in skip_hpo
    fit_and_save_model(model=model, params=dict(), fit_args=fit_model_args, predict_proba_args=predict_proba_args, y_val=y_val, time_start=time.time(), time_limit=time_limit)
  File "D:\Projects\tactory\autogluon\core\models\abstract\model_trial.py", line 73, in fit_and_save_model
    model.fit(**fit_args, time_limit=time_left, reporter=reporter)
  File "D:\Projects\tactory\autogluon\core\models\abstract\abstract_model.py", line 405, in fit
    self._fit(**kwargs)
  File "D:\Projects\tactory\autogluon\tabular\models\rf\rf_model.py", line 117, in _fit
    self.model = self.model.fit(X, y, sample_weight=sample_weight)
  File "C:\Users\john\AppData\Roaming\Python\Python37\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "D:\Anaconda3\envs\tactory\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "D:\Anaconda3\envs\tactory\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "D:\Anaconda3\envs\tactory\lib\site-packages\joblib\parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Users\john\AppData\Roaming\Python\Python37\site-packages\sklearn\ensemble\_forest.py", line 168, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "C:\Users\john\AppData\Roaming\Python\Python37\site-packages\sklearn\tree\_classes.py", line 894, in fit
    X_idx_sorted=X_idx_sorted)
  File "C:\Users\john\AppData\Roaming\Python\Python37\site-packages\sklearn\tree\_classes.py", line 276, in fit
    if max_depth <= 0:
TypeError: '<=' not supported between instances of 'Int' and 'int'
'<=' not supported between instances of 'Int' and 'int'
```

When trying to tune min_samples_leaf:

```
    rf_options = {
        # 'max_depth': ag.space.Int(5, 15),
        'min_samples_leaf': ag.space.Int(5, 25),
    }
```

I get this error:

```
  File "C:\Users\john\AppData\Roaming\Python\Python37\site-packages\sklearn\tree\_classes.py", line 220, in fit
    if not 0. < self.min_samples_leaf <= 0.5:
TypeError: '<' not supported between instances of 'float' and 'Int'
'<' not supported between instances of 'float' and 'Int'
```

When trying for Real (float):

```
    rf_options = {
        # 'max_depth': ag.space.Int(5, 15),
        'min_samples_leaf': ag.space.Real(5.0, 25.0),
    }
```

I get this error:

```
  File "C:\Users\john\AppData\Roaming\Python\Python37\site-packages\sklearn\tree\_classes.py", line 220, in fit
    if not 0. < self.min_samples_leaf <= 0.5:
TypeError: '<' not supported between instances of 'float' and 'Int'
'<' not supported between instances of 'float' and 'Int'
```

Am i doing something wrong?  Here is how I am calling autogluon:

 ```
   hyperparameters = {
        'RF': rf_options,
        # 'CAT': {},
        # 'XGB': {},
        # 'GBM': gbm_options,
        # 'XT': {},
        # 'KNN': {},
        # 'LR': {},
        # 'NN': {},
        # 'FASTAI': {},
    }

    # HPO is not performed unless hyperparameter_tune_kwargs is specified
    hyperparameter_tune_kwargs = {
        'num_trials': 5,
        'searcher': 'auto',
    }

    predictor = TabularPredictor(
        label='label',
        eval_metric='accuracy',
        path='state/autogluon').fit(X,
        # auto_stack=True,
        num_bag_folds=5,
        num_bag_sets=2, 
        num_stack_levels=3,
        hyperparameters=hyperparameters,
        hyperparameter_tune_kwargs=hyperparameter_tune_kwargs,
        time_limit=300)
```

Autogluon version:

```
autogluon==0.1.0
autogluon-contrib-nlp==0.0.1b20210201
autogluon.core==0.1.0
autogluon.extra==0.1.0
autogluon.features==0.1.0
autogluon.mxnet==0.1.0
autogluon.tabular==0.1.0
autogluon.text==0.1.0
autogluon.vision==0.1.0


```

**Comment by Innixma** [comment]
Ah, good catch!

HPO is currently disabled for RF/XT/KNN models as most users are better off tuning the other model types (GBM, CAT, XGB, NN). Tuning RF/XT/KNN has a major risk of taking up many GB or TB of disk space. It seems the error message users get when trying to do HPO on them is not clear however, so this is a bug.
