### ISSUE TITLE
Tabular crashes on AutoML Benchmark

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#106]
When attempting to run automlbenchmark, I get the following error. It disappears and everything works correctly if I update my autolguon/task/__init__.py file as follows:

```
from .base import BaseTask
from .image_classification import ImageClassification
from .object_detection import ObjectDetection
# from .text_classification import TextClassification
from .tabular_prediction import TabularPrediction
# from . import image_classification, object_detection, text_classification, tabular_prediction
```

Thus, something in text classification is causing tabular to error on automlbenchmark.

```
module 'amlb.logger' has no attribute 'new_print'
Traceback (most recent call last):
  File "/Users/neerick/workspace/automlbenchmark/automlbenchmark/amlb/benchmark.py", line 377, in run
    meta_result = framework.run(self._dataset, task_config)
  File "/Users/neerick/workspace/automlbenchmark/automlbenchmark/frameworks/autogluon/__init__.py", line 3, in run
    from .exec import run
  File "/Users/neerick/workspace/automlbenchmark/automlbenchmark/frameworks/autogluon/exec.py", line 5, in <module>
    from autogluon.task.tabular_prediction.tabular_prediction import TabularPrediction as task
  File "/Users/neerick/workspace/awslabs/autogluon/autogluon/__init__.py", line 14, in <module>
    from .task import *
  File "/Users/neerick/workspace/awslabs/autogluon/autogluon/task/__init__.py", line 4, in <module>
    from .text_classification import TextClassification
  File "/Users/neerick/workspace/awslabs/autogluon/autogluon/task/text_classification/__init__.py", line 1, in <module>
    from .predictor import *
  File "/Users/neerick/workspace/awslabs/autogluon/autogluon/task/text_classification/predictor.py", line 9, in <module>
    import gluonnlp as nlp
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/neerick/workspace/awslabs/autogluon/venv/lib/python3.6/site-packages/gluonnlp-0.8.1-py3.6.egg/gluonnlp/__init__.py", line 24, in <module>
    from . import data
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/neerick/workspace/awslabs/autogluon/venv/lib/python3.6/site-packages/gluonnlp-0.8.1-py3.6.egg/gluonnlp/data/__init__.py", line 23, in <module>
    from . import (batchify, candidate_sampler, conll, corpora, dataloader,
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/neerick/workspace/awslabs/autogluon/venv/lib/python3.6/site-packages/gluonnlp-0.8.1-py3.6.egg/gluonnlp/data/batchify/__init__.py", line 25, in <module>
    from .embedding import *
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/neerick/workspace/awslabs/autogluon/venv/lib/python3.6/site-packages/gluonnlp-0.8.1-py3.6.egg/gluonnlp/data/batchify/embedding.py", line 28, in <module>
    from ...base import _str_types
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/neerick/workspace/awslabs/autogluon/venv/lib/python3.6/site-packages/gluonnlp-0.8.1-py3.6.egg/gluonnlp/base.py", line 34, in <module>
    from numba import njit, prange, jitclass, types
  File "/Users/neerick/workspace/awslabs/autogluon/venv/lib/python3.6/site-packages/numba/__init__.py", line 25, in <module>
    from .decorators import autojit, cfunc, generated_jit, jit, njit, stencil
  File "/Users/neerick/workspace/awslabs/autogluon/venv/lib/python3.6/site-packages/numba/decorators.py", line 12, in <module>
    from .targets import registry
  File "/Users/neerick/workspace/awslabs/autogluon/venv/lib/python3.6/site-packages/numba/targets/registry.py", line 5, in <module>
    from . import cpu
  File "/Users/neerick/workspace/awslabs/autogluon/venv/lib/python3.6/site-packages/numba/targets/cpu.py", line 11, in <module>
    from .base import BaseContext, PYOBJECT
  File "/Users/neerick/workspace/awslabs/autogluon/venv/lib/python3.6/site-packages/numba/targets/base.py", line 21, in <module>
    from . import arrayobj, builtins, imputils
  File "/Users/neerick/workspace/awslabs/autogluon/venv/lib/python3.6/site-packages/numba/targets/builtins.py", line 438, in <module>
    from numba.typing.builtins import IndexValue, IndexValueType
  File "/Users/neerick/workspace/awslabs/autogluon/venv/lib/python3.6/site-packages/numba/typing/builtins.py", line 18, in <module>
    @infer_global(print)
  File "/Users/neerick/workspace/awslabs/autogluon/venv/lib/python3.6/site-packages/numba/typing/templates.py", line 850, in register_global
    if getattr(mod, val.__name__) is not val:
AttributeError: module 'amlb.logger' has no attribute 'new_print'

```

**Comment by jwmueller** [comment]
Can we close this issue?

**Comment by zhanghang1989** [comment]
Seems resolved. Reopen if happen again.

**Comment by Innixma** [comment]
This is not resolved and is still present.

**Comment by Innixma** [comment]
Found source of error:

numba is imported by TextClassification, and numba breaks AMLB when imported after amlb.logger, fixed by updating amlb source code.

I still think we should try to avoid star importing all of AutoGluon on initial import, but for now this problem is fixed.

Resolving.

**Comment by zhenlingcn** [comment]
@Innixma How did you solve that issue? I encountered the same problem.

**Comment by Innixma** [comment]
@zhenlingcn This was an issue from very long ago and the current version of AMLB functions differently by running the AMLB code in a separate environment from the framework code. If you are referring to usage of AMLB, then consider updating the version of AMLB to the latest and following their README instructions. If you are encountering this error and it isn't related to AMLB, consider opening a new GitHub issue so we can try to resolve.

**Comment by zhenlingcn** [comment]
As a matter of fact, my error has no relationship to AutoGluon. I also use numba in my package, and find that it has a conflict with the special print function of AMLB. As a result, I commented out the relevant code fragments, and it can temporarily solve my problem. Anyway, thanks for your response. @Innixma
