### ISSUE TITLE
numpy.core._exceptions.UFuncTypeError when trying to run Vision Detector Inference

### ISSUE THREAD

**Issue by Pentar0o** [awslabs/autogluon#1256]
Hi,

I've successfully train a custom Image detector but when I want to use it I have the following error : 

I've tried to use it with the :
- image path : 
result = detector.predict('IMG_2189.jpg')

OR

- as a numpy array : 
img = Image.open('IMG_2189.jpg')
numpydata = asarray(img,dtype=int) (I've tried without the int conversion)
result = detector.predict(numpydata)

and I have the same error (maybe It requires another type ?) : 

There is the Traceback of the error : 
Traceback (most recent call last):
  File "/home/penta/.local/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 142, in _na_arithmetic_op
    result = expressions.evaluate(op, left, right)
  File "/home/penta/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 235, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "/home/penta/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 69, in _evaluate_standard
    return op(a, b)
  File "/home/penta/.local/lib/python3.8/site-packages/pandas/core/ops/roperator.py", line 9, in radd
    return right + left
numpy.core._exceptions.UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 27, in <module>
    print("Resultat : " + result)
  File "/home/penta/.local/lib/python3.8/site-packages/pandas/core/ops/common.py", line 65, in new_method
    return method(self, other)
  File "/home/penta/.local/lib/python3.8/site-packages/pandas/core/arraylike.py", line 93, in __radd__
    return self._arith_method(other, roperator.radd)
  File "/home/penta/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 5982, in _arith_method
    new_data = self._dispatch_frame_op(other, op, axis=axis)
  File "/home/penta/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 6008, in _dispatch_frame_op
    bm = self._mgr.apply(array_op, right=right)
  File "/home/penta/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 425, in apply
    applied = b.apply(f, **kwargs)
  File "/home/penta/.local/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 378, in apply
    result = func(self.values, **kwargs)
  File "/home/penta/.local/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 189, in arithmetic_op
    res_values = _na_arithmetic_op(lvalues, rvalues, op)
  File "/home/penta/.local/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 149, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
  File "/home/penta/.local/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 111, in _masked_arith_op
    result[mask] = op(xrav[mask], y)
  File "/home/penta/.local/lib/python3.8/site-packages/pandas/core/ops/roperator.py", line 9, in radd
    return right + left
numpy.core._exceptions.UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')

Thanks for your help.

Regards.

**Comment by yinweisu** [comment]
Hi,

Object detector is able to take str(filepath), pd.DataFrame with 'image' column, or raw ndarray input. I've verified that all of these input type is working well. I suspect there's something weird going on with your image. If you look at the traceback, the code is not going into autogluon vision. Will close this issue
