### ISSUE TITLE
Error of rlscheduler when tuning pytorch model

### ISSUE THREAD

**Issue by YiwenAI** [awslabs/autogluon#1287]
Hi,

I've successfully tuned pytorch model on MNIST just as the tutorial does. However, when I want to change the scheduler from basic ones to RLscheduler, I have the key error of 'choice'.

Here is my code, by the way, I have changed the space into Categorical.

searcher = RLSearcher(ag_train_mnist.kwspaces)
myscheduler = ag.scheduler.RLScheduler(
        ag_train_mnist,
        searcher = searcher,
        resource={'num_cpus': 1, 'num_gpus': 1},
        num_trials=300,
        reward_attr='accuracy',
        controller_batch_size=4,
        controller_lr=5e-3)
myscheduler.run()
myscheduler.join_jobs()

And this is the error traceback:

Traceback (most recent call last):
  File "/home/rl253/anaconda3/envs/autogluon/lib/python3.7/site-packages/autogluon/core/utils/custom_process.py", line 16, in run
    mp.Process.run(self)
  File "/home/rl253/anaconda3/envs/autogluon/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rl253/anaconda3/envs/autogluon/lib/python3.7/site-packages/autogluon/core/scheduler/jobs.py", line 60, in _worker
    ret = fn(**args)
  File "/home/rl253/anaconda3/envs/autogluon/lib/python3.7/site-packages/autogluon/core/decorator.py", line 54, in __call__
    args = sample_config(args, new_config)
  File "/home/rl253/anaconda3/envs/autogluon/lib/python3.7/site-packages/autogluon/core/decorator.py", line 34, in sample_config
    args_dict[k] = v.sample(**sub_config)
  File "/home/rl253/anaconda3/envs/autogluon/lib/python3.7/site-packages/autogluon/core/decorator.py", line 279, in sample
    kwargs[k] = kwspaces[k].sample(**sub_config)
  File "/home/rl253/anaconda3/envs/autogluon/lib/python3.7/site-packages/autogluon/core/space.py", line 377, in sample
    choice = config.pop('choice')
KeyError: 'choice'
NoneType: None

May I ask whether there exists a bug or I use the API wrong? Thank you for your help!

**Comment by Innixma** [comment]
@mseeger Perhaps you could answer this?

**Comment by Innixma** [comment]
Closing as we are removing RLScheduler in v0.4 as part of an HPO overhaul.
