### ISSUE TITLE
IndexError on Tabular Predictor fit() with hyperparameter tuning and num_bag_folds

### ISSUE THREAD

**Issue by lebatchelor** [awslabs/autogluon#1357]
IndexError: list index out of range is thrown when running Tabular Predictor fit() method with below config:

tabular_predictor = TabularPredictor(
            label=target_variable,
            problem_type='regression',
            eval_metric='mean_absolute_error',
            path=model_output_path,
        ).fit(
            train_data=model_training_dat,
            tuning_data=model_tuning_dat,
            feature_metadata=self.feature_metadata,
            hyperparameters={'CAT': {}, 'XGB': {}, 'GBM': [{}, {'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}]},
            hyperparameter_tune_kwargs='auto',
            presets='medium_quality_faster_train',
            use_bag_holdout=True,
            num_bag_folds=2,
            num_bag_sets=2,
            keep_only_best=True,
            save_space=True
        )

We have tested it the same but with num_bag_folds removed and it works.
It also works when using excluded_model_types: ['NN', 'FASTAI', 'KNN', 'RF', 'XT'] and removing hyperparameters and hyperparameter_tune_kwargs. 
We have tested on different data also and same behaviour is shown. 

Version 0.3.1
MacOS Big Sur and Ubuntu 18.04

Beginning AutoGluon training ...
AutoGluon will save models to "agModels/cpc_regression_model/20211028_111324/"
AutoGluon Version:  0.3.1
Train Data Rows:    591757
Train Data Columns: 111
Tuning Data Rows:    8098
Tuning Data Columns: 111
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6930.83 MB
	Train Data (Original)  Memory Usage: 555.91 MB (8.0% of available memory)
	Warning: Data size prior to feature transformation consumes 8.0% of available memory. Consider increasing memory or subsampling the data to avoid instability.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			WARNING: Actual dtype differs from dtype in FeatureMetadata for feature "domain". Actual dtype: int | Expected dtype: category
			WARNING: Actual dtype differs from dtype in FeatureMetadata for feature "day_of_week". Actual dtype: object | Expected dtype: category
			WARNING: Actual dtype differs from dtype in FeatureMetadata for feature "month_of_year". Actual dtype: object | Expected dtype: category
			WARNING: Actual dtype differs from dtype in FeatureMetadata for feature "device". Actual dtype: object | Expected dtype: category
			WARNING: Actual dtype differs from dtype in FeatureMetadata for feature "target_type". Actual dtype: object | Expected dtype: category
			WARNING: Actual dtype differs from dtype in FeatureMetadata for feature "impressions". Actual dtype: int | Expected dtype: float
			WARNING: Forcefully converting features to expected dtypes. Please manually align the input data with the expected dtypes if issues occur.
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['search_term', 'canonical_name']
			CountVectorizer fit with vocabulary size = 6475
		Warning: Due to memory constraints, ngram feature count is being reduced. Allocate more memory to maximize model quality.
		Reducing Vectorizer vocab size from 6475 to 347 to avoid OOM error
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Useless Original Features (Count: 1): ['ad_type']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('category', [])     : 5 | ['domain', 'day_of_week', 'month_of_year', 'device', 'target_type']
		('datetime', [])     : 2 | ['date', 'month']
		('float', [])        : 1 | ['impressions']
		('object', ['text']) : 2 | ['search_term', 'canonical_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    :   3 | ['domain', 'day_of_week', 'target_type']
		('category', ['text_as_category'])  :   2 | ['search_term', 'canonical_name']
		('float', [])                       :   1 | ['impressions']
		('int', ['binned', 'text_special']) :  17 | ['search_term.char_count', 'search_term.word_count', 'search_term.lower_ratio', 'search_term.digit_ratio', 'search_term.special_ratio', ...]
		('int', ['bool'])                   :   3 | ['month', 'month_of_year', 'device']
		('int', ['datetime_as_int'])        :   1 | ['date']
		('int', ['text_ngram'])             : 348 | ['__nlp__.2021', '__nlp__.2021 mercedes', '__nlp__.2021 mercedes benz', '__nlp__.2021 south', '__nlp__.2021 south los', ...]
	194.6s = Fit runtime
	10 features in original data used to generate 375 features in processed data.
	Train Data (Processed) Memory Usage: 444.5 MB (5.0% of available memory)
Data preprocessing and feature engineering runtime = 199.11s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_absolute_error'
	To change this, specify the eval_metric argument of fit()
Fitting 4 L1 models ...
Hyperparameter tuning model: LightGBM_BAG_L1 ...
  0%|          | 0/1 [00:00<?, ?it/s][1000]	train_set's l1: 0.315377	valid_set's l1: 0.341291
[2000]	train_set's l1: 0.297136	valid_set's l1: 0.332526
[3000]	train_set's l1: 0.284798	valid_set's l1: 0.327476
[4000]	train_set's l1: 0.276148	valid_set's l1: 0.324443
[5000]	train_set's l1: 0.268395	valid_set's l1: 0.321814
[6000]	train_set's l1: 0.261501	valid_set's l1: 0.319515
[7000]	train_set's l1: 0.255617	valid_set's l1: 0.317695
[8000]	train_set's l1: 0.250368	valid_set's l1: 0.316108
[9000]	train_set's l1: 0.245713	valid_set's l1: 0.314794
[10000]	train_set's l1: 0.241187	valid_set's l1: 0.313629
100%|██████████| 1/1 [06:18<00:00, 378.13s/it]
Fitted model: LightGBM_BAG_L1/T0 ...
	-0.3136	 = Validation score   (mean_absolute_error)
	221.92s	 = Training   runtime
	152.6s	 = Validation runtime
Hyperparameter tuning model: LightGBMXT_BAG_L1 ...
  0%|          | 0/1 [00:00<?, ?it/s][1000]	train_set's l1: 0.360635	valid_set's l1: 0.369533
[2000]	train_set's l1: 0.34069	valid_set's l1: 0.355585
[3000]	train_set's l1: 0.328267	valid_set's l1: 0.348154
[4000]	train_set's l1: 0.318847	valid_set's l1: 0.3432
[5000]	train_set's l1: 0.311437	valid_set's l1: 0.339764
[6000]	train_set's l1: 0.305322	valid_set's l1: 0.337344
[7000]	train_set's l1: 0.299978	valid_set's l1: 0.335335
[8000]	train_set's l1: 0.295221	valid_set's l1: 0.333648
[9000]	train_set's l1: 0.291167	valid_set's l1: 0.332493
[10000]	train_set's l1: 0.287352	valid_set's l1: 0.331406
100%|██████████| 1/1 [02:50<00:00, 170.07s/it]
Fitted model: LightGBMXT_BAG_L1/T0 ...
	-0.3314	 = Validation score   (mean_absolute_error)
	108.16s	 = Training   runtime
	60.83s	 = Validation runtime
Hyperparameter tuning model: CatBoost_BAG_L1 ...
100%|██████████| 1/1 [17:49<00:00, 1069.78s/it]
Fitted model: CatBoost_BAG_L1/T0 ...
	-0.339	 = Validation score   (mean_absolute_error)
	1063.66s	 = Training   runtime
	3.07s	 = Validation runtime
Hyperparameter tuning model: XGBoost_BAG_L1 ...
100%|██████████| 1/1 [01:16<00:00, 76.99s/it]
Fitted model: XGBoost_BAG_L1/T0 ...
	-0.3585	 = Validation score   (mean_absolute_error)
	67.77s	 = Training   runtime
	7.23s	 = Validation runtime
Fitting model: LightGBM_BAG_L1/T0 ...
	Warning: Exception caused LightGBM_BAG_L1/T0 to fail during training... Skipping this model.
		list index out of range
Detailed Traceback:
Traceback (most recent call last):
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/tabular/trainer/abstract_trainer.py", line 962, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/tabular/trainer/abstract_trainer.py", line 934, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/abstract/abstract_model.py", line 522, in fit
    out = self._fit(**kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 153, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 189, in _fit
    n_repeats=n_repeats, n_repeat_start=n_repeat_start, save_folds=save_bag_folds, groups=groups, **kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 378, in _fit_folds
    fold=kfolds[i],
IndexError: list index out of range
Fitting model: LightGBMXT_BAG_L1/T0 ...
	Warning: Exception caused LightGBMXT_BAG_L1/T0 to fail during training... Skipping this model.
		list index out of range
Detailed Traceback:
Traceback (most recent call last):
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/tabular/trainer/abstract_trainer.py", line 962, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/tabular/trainer/abstract_trainer.py", line 934, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/abstract/abstract_model.py", line 522, in fit
    out = self._fit(**kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 153, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 189, in _fit
    n_repeats=n_repeats, n_repeat_start=n_repeat_start, save_folds=save_bag_folds, groups=groups, **kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 378, in _fit_folds
    fold=kfolds[i],
IndexError: list index out of range
Fitting model: CatBoost_BAG_L1/T0 ...
	Warning: Exception caused CatBoost_BAG_L1/T0 to fail during training... Skipping this model.
		list index out of range
Detailed Traceback:
Traceback (most recent call last):
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/tabular/trainer/abstract_trainer.py", line 962, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/tabular/trainer/abstract_trainer.py", line 934, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/abstract/abstract_model.py", line 522, in fit
    out = self._fit(**kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 153, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 189, in _fit
    n_repeats=n_repeats, n_repeat_start=n_repeat_start, save_folds=save_bag_folds, groups=groups, **kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 378, in _fit_folds
    fold=kfolds[i],
IndexError: list index out of range
Fitting model: XGBoost_BAG_L1/T0 ...
	Warning: Exception caused XGBoost_BAG_L1/T0 to fail during training... Skipping this model.
		list index out of range
Detailed Traceback:
Traceback (most recent call last):
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/tabular/trainer/abstract_trainer.py", line 962, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/tabular/trainer/abstract_trainer.py", line 934, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/abstract/abstract_model.py", line 522, in fit
    out = self._fit(**kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 153, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 189, in _fit
    n_repeats=n_repeats, n_repeat_start=n_repeat_start, save_folds=save_bag_folds, groups=groups, **kwargs)
  File "/Users/laurabatchelor/github/adthena-cpc/py/lib/python3.6/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 378, in _fit_folds
    fold=kfolds[i],
IndexError: list index out of range
No base models to train on, skipping weighted ensemble...

**Comment by Innixma** [comment]
Thanks for creating a github issue!

I tried to reproduce this but was not able to, please refer to the colab notebook: https://colab.research.google.com/drive/1vFyLQZd4HPGyMAfoflRKJHAg4AzuhYNQ?usp=sharing

If you can provide a reproducible example, that would be very helpful.

**Comment by lebatchelor** [comment]
Hi @Innixma thanks for having a look. I have created a reproduction here in colab notebook for you: https://colab.research.google.com/drive/1eH8O323FimwovSd4gTfW8GrJL6m596bi?usp=sharing

**Comment by Innixma** [comment]
Hi @lebatchelor, thank you very much for the notebook, it was key to locating the bug!

This has been fixed in #1365.

Here is an update to your colab notebook showcasing the fix: https://colab.research.google.com/drive/1fSNoWUqOMjp_6nXRv0cDjFi5OGEGDip2?usp=sharing

Once merged, it will be available in nightly pre-release the day after.
Here are the instructions to install the nightly pre-release: https://auto.gluon.ai/dev/index.html

**Comment by lebatchelor** [comment]
Great news, thanks for fixing so quickly @Innixma!
