### ISSUE TITLE
WARNING: Encountered unexpected exception during trial 6, stopping HPO early.

### ISSUE THREAD

**Issue by Weixin-Liang** [awslabs/autogluon#1481]
Hi, thanks for creating such a wonderful AutoML framework! 

It seems that there is an "unexpected exception" when I asked the framework to optimize for a larger `num_trials`. Do you happen to have an idea of what exactly is the "unexpected exception", and how to solve that? Many thanks! 

To reproduce: 
```py
from autogluon.vision import ImagePredictor, ImageDataset

train_dataset, _, test_dataset = ImageDataset.from_folders('https://autogluon.s3.amazonaws.com/datasets/shopee-iet.zip')

predictor = ImagePredictor(verbosity=4)
predictor.fit(train_dataset, time_limit=999999, 
              hyperparameter_tune_kwargs={'num_trials': 10})
```

The log looks like the following: 
```plain
[Epoch 14] speed: 184 samples/sec       time cost: 3.815730
[Epoch 14] validation: top1=0.937500 top5=1.000000
Applying the state from the best checkpoint...
Reporter Done!
 60%|███████████████████████████████████▍                       | 6/10 [06:38<04:30, 67.52s/it]
WARNING: Encountered unexpected exception during trial 6, stopping HPO early.
 60%|███████████████████████████████████▍                       | 6/10 [06:38<04:25, 66.37s/it]
Reporter Done!
Finished, total runtime is 399.96 s
```

**Comment by Innixma** [comment]
This error has been clarified in pre-release / upcoming v0.4 release:

```
Applying the state from the best checkpoint...
 60%|██████████████████████████▍                 | 6/10 [00:49<00:30,  7.66s/it]	WARNING: Encountered unexpected exception during trial 6, stopping HPO early.
Detailed Traceback:
Traceback (most recent call last):
  File "/home/ubuntu/remote2/autogluon/core/src/autogluon/core/scheduler/seq_scheduler.py", line 157, in run
    is_failed, result = self.run_trial(task_id=i)
  File "/home/ubuntu/remote2/autogluon/core/src/autogluon/core/scheduler/seq_scheduler.py", line 238, in run_trial
    new_searcher_config = self.searcher.get_config()
  File "/home/ubuntu/remote2/autogluon/core/src/autogluon/core/searcher/local_random_searcher.py", line 56, in get_config
    assert num_tries <= self.MAX_RETRIES, f"Cannot find new config in LocalRandomSearcher, even after {self.MAX_RETRIES} trials"
AssertionError: Cannot find new config in LocalRandomSearcher, even after 100 trials
 60%|██████████████████████████▍                 | 6/10 [00:49<00:33,  8.28s/it]
Finished, total runtime is 50.04 s
```

Essentially the default search space only contains 6 possible unique hyperparameter values, so there is nothing left to search after the 6th trial. You can specify a custom search space to overcome this.
