### ISSUE TITLE
mac 安装autogluon  import lightgbm error

### ISSUE THREAD

**Issue by chestnut111** [awslabs/autogluon#1501]
`>>> import lightgbm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wanglixin03/opt/anaconda3/envs/agg/lib/python3.8/site-packages/lightgbm/__init__.py", line 8, in <module>
    from .basic import Booster, Dataset, Sequence, register_logger
  File "/Users/wanglixin03/opt/anaconda3/envs/agg/lib/python3.8/site-packages/lightgbm/basic.py", line 110, in <module>
    _LIB = _load_lib()
  File "/Users/wanglixin03/opt/anaconda3/envs/agg/lib/python3.8/site-packages/lightgbm/basic.py", line 101, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/Users/wanglixin03/opt/anaconda3/envs/agg/lib/python3.8/ctypes/__init__.py", line 447, in LoadLibrary
    return self._dlltype(name)
  File "/Users/wanglixin03/opt/anaconda3/envs/agg/lib/python3.8/ctypes/__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/wanglixin03/opt/anaconda3/envs/agg/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/wanglixin03/opt/anaconda3/envs/agg/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)`

**Comment by Innixma** [comment]
You are missing the libomp dependency. You must first do:

```
# brew install wget
wget https://raw.githubusercontent.com/Homebrew/homebrew-core/fb8323f2b170bd4ae97e1bac9bf3e2983af3fdb0/Formula/libomp.rb
# Uninstall libomp if it was previous installed
# brew uninstall libomp
brew install libomp.rb
rm libomp.rb
```

Refer to installation instructions for more details: https://auto.gluon.ai/dev/index.html

**Comment by chestnut111** [comment]
i tryed it , but not work ....

**Comment by Innixma** [comment]
@chestnut111 

Your issue is not related to AutoGluon, it is related to LightGBM. You can simplify your situation with:

```
import torch
import lightgbm
```

vs

```
import lightgbm
import torch
```

Please refer to https://github.com/microsoft/LightGBM/issues/4897 for more details.
