### ISSUE TITLE
setup.py install does not work correctly

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#171]
Code ran on Linux EC2 instance.

Our documentation on installing AutoGluon from source says to use python setup.py install, however, this code does not work to create a functioning AutoGluon:

```
git clone https://github.com/awslabs/autogluon
cd autogluon
sudo apt-get install -y python3-venv
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install --upgrade mxnet
python setup.py install
```

This code works:

```
git clone https://github.com/awslabs/autogluon
cd autogluon
sudo apt-get install -y python3-venv
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install --upgrade mxnet
python setup.py develop
```

Why does setup.py install not properly install AutoGluon?

**Comment by StacyYang** [comment]
What is the error message if setup install?

**Comment by Innixma** [comment]
In python:

`from autogluon import TabularPrediction as task`

Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/workspace/test_ag/autogluon/autogluon/__init__.py", line 6, in <module>
    from .utils.try_import import *
  File "/home/ubuntu/workspace/test_ag/autogluon/autogluon/utils/__init__.py", line 1, in <module>
    from .files import *
  File "/home/ubuntu/workspace/test_ag/autogluon/autogluon/utils/files.py", line 9, in <module>
    from .tqdm import tqdm
  File "/home/ubuntu/workspace/test_ag/autogluon/autogluon/utils/tqdm.py", line 4, in <module>
    from tqdm import tqdm as base
ModuleNotFoundError: No module named 'tqdm'

```

pip freeze:

```
autogluon==0.0.3+c56beb9
certifi==2019.11.28
chardet==3.0.4
graphviz==0.8.4
idna==2.8
mxnet==1.5.1.post0
numpy==1.17.4
requests==2.22.0
urllib3==1.25.7
```
pip freeze when calling setup.py develop (working version):

```
-e git+https://github.com/awslabs/autogluon@c56beb911d3c1184421bc7dec4e9b78dde68d700#egg=autogluon
bcrypt==3.1.7
boto3==1.9.187
botocore==1.12.253
catboost==0.20.1
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
Click==7.0
cloudpickle==1.2.2
ConfigSpace==0.4.10
cryptography==2.8
cycler==0.10.0
Cython==0.29.14
dask==2.9.0
distributed==2.9.0
docutils==0.15.2
gluoncv==0.6.0b20191221
gluonnlp==0.8.1
graphviz==0.8.4
HeapDict==1.0.1
idna==2.8
jmespath==0.9.4
joblib==0.14.1
kiwisolver==1.1.0
lightgbm==2.3.0
matplotlib==3.2.0rc1
msgpack==1.0.0rc1
mxnet==1.5.1.post0
numpy==1.17.4
pandas==0.24.2
paramiko==2.7.1
Pillow==6.2.1
plotly==4.4.1
portalocker==1.5.2
psutil==5.6.7
pycparser==2.19
PyNaCl==1.3.0
pyparsing==2.4.5
python-dateutil==2.8.1
pytz==2019.3
PyYAML==5.3b1
requests==2.22.0
retrying==1.3.3
s3transfer==0.2.1
scikit-learn==0.21.2
scikit-optimize==0.5.2
scipy==1.4.1
six==1.13.0
sortedcontainers==2.1.0
tblib==1.6.0
toolz==0.10.0
tornado==6.0.3
tqdm==4.41.0
typing==3.7.4.1
urllib3==1.25.7
zict==1.0.0
```

**Comment by zhanghang1989** [comment]
The error looks like you don't have `tqdm` installed. Try `pip install tqdm`

**Comment by larroy** [comment]
Similar happens with Numpy and ConfigSpace:


this is a fresh virtualenv, it works if I install numpy manually before.

```
(py3) pllarroy@u1f72896d8fa75d:1:~/devel/autogluon$ pip install -e .
Obtaining file:///home/ANT.AMAZON.COM/pllarroy/devel/autogluon
Collecting numpy>=1.16.0
  Using cached https://files.pythonhosted.org/packages/92/e6/45f71bd24f4e37629e9db5fb75caab919507deae6a5a257f9e4685a5f931/numpy-1.18.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy>=1.3.3
  Using cached https://files.pythonhosted.org/packages/dc/29/162476fd44203116e7980cfbd9352eef9db37c49445d1fec35509022f6aa/scipy-1.4.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting cython
  Using cached https://files.pythonhosted.org/packages/df/d1/4d3f8a7a920e805488a966cc6ab55c978a712240f584445d703c08b9f405/Cython-0.29.14-cp36-cp36m-manylinux1_x86_64.whl
Collecting tornado
  Using cached https://files.pythonhosted.org/packages/30/78/2d2823598496127b21423baffaa186b668f73cd91887fcef78b6eade136b/tornado-6.0.3.tar.gz
Collecting requests
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting matplotlib
  Using cached https://files.pythonhosted.org/packages/4e/11/06958a2b895a3853206dea1fb2a5b11bf044f626f90745987612af9c8f2c/matplotlib-3.1.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting tqdm>=4.38.0
  Using cached https://files.pythonhosted.org/packages/8c/c3/d049cf3fb31094ee045ec1ee29fffac218c91e82c8838c49ab4c3e52627b/tqdm-4.41.0-py2.py3-none-any.whl
Collecting paramiko>=2.5.0
  Using cached https://files.pythonhosted.org/packages/06/1e/1e08baaaf6c3d3df1459fd85f0e7d2d6aa916f33958f151ee1ecc9800971/paramiko-2.7.1-py2.py3-none-any.whl
Collecting distributed>=2.6.0
  Using cached https://files.pythonhosted.org/packages/c1/45/1c741b907b7aa60a7a951e3cb107f1c3cda40fc368c2ff21a0bb58029aee/distributed-2.9.0-py3-none-any.whl
Collecting ConfigSpace<=0.4.10
  Using cached https://files.pythonhosted.org/packages/42/de/4e8e4f26332fc65404f52baa112defbf822b6738b60bfa6b2993f5c60933/ConfigSpace-0.4.10.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/ANT.AMAZON.COM/pllarroy/devel/autogluon/py3/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pt50q63e/ConfigSpace/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pt50q63e/ConfigSpace/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-pt50q63e/ConfigSpace/pip-egg-info
         cwd: /tmp/pip-install-pt50q63e/ConfigSpace/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pt50q63e/ConfigSpace/setup.py", line 4, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Innixma** [comment]
> The error looks like you don't have `tqdm` installed. Try `pip install tqdm`

tqdm is not the problem, it is in the required install list of AutoGluon, the problem is it does not attempt to install any of these packages when doing python setup.py install

**Comment by larroy** [comment]
Can't we use the latest ConfigSpace? I tried pinning it to 0.4.11 but I get this error:

I didn't dive deep into this.

```


  ERROR: Command errored out with exit status 1:
   command: /Users/pllarroy/devel/autogluon/py3/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rr/sj1ts20x6tzff6t2580ttyd933647b/T/pip-install-8l6db847/ConfigSpace/setup.py'"'"'; __file__='"'"'/private/var/folders/rr/sj1ts20x6tzff6t2580ttyd933647b/T/pip-install-8l6db847/ConfigSpace/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/rr/sj1ts20x6tzff6t2580ttyd933647b/T/pip-wheel-95pc_6rf --python-tag cp37
       cwd: /private/var/folders/rr/sj1ts20x6tzff6t2580ttyd933647b/T/pip-install-8l6db847/ConfigSpace/
  Complete output (56 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-x86_64-3.7
  creating build/lib.macosx-10.14-x86_64-3.7/test
  copying test/test_configuration_space.py -> build/lib.macosx-10.14-x86_64-3.7/test
  copying test/test_forbidden.py -> build/lib.macosx-10.14-x86_64-3.7/test
  copying test/test_conditions.py -> build/lib.macosx-10.14-x86_64-3.7/test
  copying test/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/test
  copying test/test_util.py -> build/lib.macosx-10.14-x86_64-3.7/test
  copying test/test_hyperparameters.py -> build/lib.macosx-10.14-x86_64-3.7/test
  creating build/lib.macosx-10.14-x86_64-3.7/ConfigSpace
  copying ConfigSpace/convert.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace
  copying ConfigSpace/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace
  copying ConfigSpace/__version__.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace
  copying ConfigSpace/exceptions.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace
  creating build/lib.macosx-10.14-x86_64-3.7/test/test_searchspaces
  copying test/test_searchspaces/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/test/test_searchspaces
  creating build/lib.macosx-10.14-x86_64-3.7/test/test_converters_and_test_searchspaces
  copying test/test_converters_and_test_searchspaces/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/test/test_converters_and_test_searchspaces
  copying test/test_converters_and_test_searchspaces/test_sample_configuration_spaces.py -> build/lib.macosx-10.14-x86_64-3.7/test/test_converters_and_test_searchspaces
  creating build/lib.macosx-10.14-x86_64-3.7/test/read_and_write
  copying test/read_and_write/test_pyll_util.py -> build/lib.macosx-10.14-x86_64-3.7/test/read_and_write
  copying test/read_and_write/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/test/read_and_write
  copying test/read_and_write/test_pb_converter.py -> build/lib.macosx-10.14-x86_64-3.7/test/read_and_write
  copying test/read_and_write/test_json.py -> build/lib.macosx-10.14-x86_64-3.7/test/read_and_write
  copying test/read_and_write/test_pcs_converter.py -> build/lib.macosx-10.14-x86_64-3.7/test/read_and_write
  copying test/read_and_write/test_irace_writer.py -> build/lib.macosx-10.14-x86_64-3.7/test/read_and_write
  creating build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/nx
  copying ConfigSpace/nx/exception.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/nx
  copying ConfigSpace/nx/release.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/nx
  copying ConfigSpace/nx/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/nx
  creating build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/read_and_write
  copying ConfigSpace/read_and_write/pcs_new.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/read_and_write
  copying ConfigSpace/read_and_write/pyll.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/read_and_write
  copying ConfigSpace/read_and_write/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/read_and_write
  copying ConfigSpace/read_and_write/spearmint_april2013_mod_spearmint_pb2.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/read_and_write
  copying ConfigSpace/read_and_write/json.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/read_and_write
  copying ConfigSpace/read_and_write/irace.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/read_and_write
  copying ConfigSpace/read_and_write/pbs.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/read_and_write
  copying ConfigSpace/read_and_write/pcs.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/read_and_write
  creating build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/nx/classes
  copying ConfigSpace/nx/classes/graph.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/nx/classes
  copying ConfigSpace/nx/classes/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/nx/classes
  copying ConfigSpace/nx/classes/digraph.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/nx/classes
  creating build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/nx/algorithms
  copying ConfigSpace/nx/algorithms/dag.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/nx/algorithms
  copying ConfigSpace/nx/algorithms/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/nx/algorithms
  copying ConfigSpace/nx/algorithms/cycles.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/nx/algorithms
  creating build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/nx/algorithms/components
  copying ConfigSpace/nx/algorithms/components/strongly_connected.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/nx/algorithms/components
  copying ConfigSpace/nx/algorithms/components/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/ConfigSpace/nx/algorithms/components
  running build_ext
  building 'ConfigSpace.hyperparameters' extension
  error: unknown file type '.pyx' (from 'ConfigSpace/hyperparameters.pyx')
  ----------------------------------------
  ERROR: Failed building wheel for ConfigSpace

```

**Comment by larroy** [comment]
Yes the main issue is that tdqm should be installed by ConfigSpace if it's a ConfigSpace dependency. Otherwise we could mitigate by listing tdqm in autogluon explicitly.

**Comment by larroy** [comment]
Just installed `c75f99c9605938876a6a47a54d64100f9a61a504` in mac in a clean virtualenv and didn't see the issue .


In Linux installing from pip the issue appears as described above (numpy missing from ConfigSpace).

**Comment by Innixma** [comment]
We fixed this in #180 , the instructions were incorrect and it should be setup.py develop. Are you referring to a different issue @larroy ?

**Comment by larroy** [comment]
I just did this now in master:

Ubuntu 18.04 fresh, the below commands fail with error below, because numpy is not installed globally. When numpy is installed in the global scope (as I have on my mac, the installation suceeds). This is a problem with installation or the dependency closure.

```
git clone git@github.com:awslabs/autogluon.git
virtualenv -p`which python3` py3
source py3/bin/activate
cd autogluon
pip install -e .
[...]

Collecting ConfigSpace<=0.4.10
  Using cached https://files.pythonhosted.org/packages/42/de/4e8e4f26332fc65404f52baa112defbf822b6738b60bfa6b2993f5c60933/ConfigSpace-0.4.10.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/piotr/autogluon/py3/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2kg3m7o1/ConfigSpace/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2kg3m7o1/ConfigSpace/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-2kg3m7o1/ConfigSpace/pip-egg-info
         cwd: /tmp/pip-install-2kg3m7o1/ConfigSpace/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2kg3m7o1/ConfigSpace/setup.py", line 4, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by larroy** [comment]
Using `python setup.py develop` has the same issue.

**Comment by Innixma** [comment]
Can you try:

```
pip install --upgrade mxnet
python setup.py develop
```

**Comment by larroy** [comment]
Yeah well, that's is going to install numpy, which will fix the issue, so I guess it will work, the package should install self-sufficiently without errors.

**Comment by Innixma** [comment]
That would require us to install mxnet during the setup.py call. I remember us making the decision not to do this in the past.

@zhanghang1989 What was the reason for not installing mxnet in AutoGluon's setup.py? This would simplify installation to a 1-liner. Users could still install a particular version of mxnet prior to installing AutoGluon to retain the previous functionality.

**Comment by zhanghang1989** [comment]
> That would require us to install mxnet during the setup.py call. I remember us making the decision not to do this in the past.
> 
> @zhanghang1989 What was the reason for not installing mxnet in AutoGluon's setup.py? This would simplify installation to a 1-liner. Users could still install a particular version of mxnet prior to installing AutoGluon to retain the previous functionality.

MxNet has multiple CUDA versions, which should be specified by the user. @larroy knows that.
If MxNet support conda, it would be a lot easier. However, this requires significant amount of effort from MxNet team.

**Comment by Innixma** [comment]
The primary issue that this was created for has been resolved. The installation instructions now work. Closing this issue. @larroy if you have additional concerns regarding the installation, please open a new issue so we can focus attention.

Best,
Nick

**Comment by larroy** [comment]
That works, since installing mxnet installs numpy.

**Comment by larroy** [comment]
Issue regarding pip install not having numpy / Configspace remains, just had it again on windows.

```
PS C:\Users\Administrator> pip install autogluon
Collecting autogluon
  Downloading autogluon-0.0.5-py3-none-any.whl (328 kB)
     |████████████████████████████████| 328 kB 6.8 MB/s
Collecting scikit-optimize
  Downloading scikit_optimize-0.7.2-py2.py3-none-any.whl (80 kB)
     |████████████████████████████████| 80 kB 5.1 MB/s
Collecting catboost
  Downloading catboost-0.21-cp37-none-win_amd64.whl (63.4 MB)
     |████████████████████████████████| 63.4 MB 197 kB/s
Collecting paramiko>=2.5.0
  Downloading paramiko-2.7.1-py2.py3-none-any.whl (206 kB)
     |████████████████████████████████| 206 kB ...
Collecting scipy>=1.3.3
  Downloading scipy-1.4.1-cp37-cp37m-win_amd64.whl (30.9 MB)
     |████████████████████████████████| 30.9 MB 228 kB/s
Collecting scikit-learn==0.21.2
  Downloading scikit_learn-0.21.2-cp37-cp37m-win_amd64.whl (5.9 MB)
     |████████████████████████████████| 5.9 MB ...
Collecting numpy>=1.16.0
  Downloading numpy-1.18.1-cp37-cp37m-win_amd64.whl (12.8 MB)
     |████████████████████████████████| 12.8 MB ...
Collecting gluoncv>=0.5.0
  Downloading gluoncv-0.6.0-py2.py3-none-any.whl (693 kB)
     |████████████████████████████████| 693 kB ...
Collecting lightgbm==2.3.0
  Downloading lightgbm-2.3.0-py2.py3-none-win_amd64.whl (543 kB)
     |████████████████████████████████| 543 kB ...
Requirement already satisfied: requests in c:\python37\lib\site-packages (from autogluon) (2.22.0)
Collecting Pillow<=6.2.1
  Downloading Pillow-6.2.1-cp37-cp37m-win_amd64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB ...
Collecting cython
  Downloading Cython-0.29.15-cp37-cp37m-win_amd64.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB ...
Collecting matplotlib
  Downloading matplotlib-3.1.3-cp37-cp37m-win_amd64.whl (9.1 MB)
     |████████████████████████████████| 9.1 MB 6.4 MB/s
Requirement already satisfied: psutil>=5.0.0 in c:\python37\lib\site-packages (from autogluon) (5.6.7)
Collecting tqdm>=4.38.0
  Downloading tqdm-4.42.1-py2.py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB ...
Collecting distributed==2.6.0
  Downloading distributed-2.6.0-py3-none-any.whl (560 kB)
     |████████████████████████████████| 560 kB ...
Collecting pandas<1.0,>=0.24.0
  Downloading pandas-0.25.3-cp37-cp37m-win_amd64.whl (9.2 MB)
     |████████████████████████████████| 9.2 MB 6.4 MB/s
Collecting boto3==1.9.187
  Downloading boto3-1.9.187-py2.py3-none-any.whl (128 kB)
     |████████████████████████████████| 128 kB 6.8 MB/s
Collecting gluonnlp==0.8.1
  Downloading gluonnlp-0.8.1.tar.gz (236 kB)
     |████████████████████████████████| 236 kB ...
Collecting graphviz
  Downloading graphviz-0.13.2-py2.py3-none-any.whl (17 kB)
Collecting cryptography>=2.8
  Downloading cryptography-2.8-cp37-cp37m-win_amd64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 6.8 MB/s
Collecting ConfigSpace<=0.4.10
  Downloading ConfigSpace-0.4.10.tar.gz (882 kB)
     |████████████████████████████████| 882 kB 6.4 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-install-ax0fjbes\\ConfigSpace\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-install-ax0fjbes\\ConfigSpace\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-ax0fjbes\ConfigSpace\pip-egg-info'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-ax0fjbes\ConfigSpace\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-ax0fjbes\ConfigSpace\setup.py", line 4, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Innixma** [comment]
So you are saying that pip install mxnet does not install numpy?

**Comment by Innixma** [comment]
Marking this issue as resolved since the website instructions are correct.
