### ISSUE TITLE
[BUG] Ray/grpc: failed to connect to all addresses

### ISSUE THREAD

**Issue by nilsplettenberg** [awslabs/autogluon#1713]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
We're running autogluon in kind pods. For some datasets, we get an error from ray. 

Full stacktrace:
```
Preset alias specified: 'high_quality_fast_inference_only_refit' maps to 'high_quality'.                                                                                              
 Presets specified: ['high_quality_fast_inference_only_refit', 'optimize_for_deployment']                                                                                              
 Beginning AutoGluon training ... Time limit = 180s                                                                                                                                    
 AutoGluon will save models to "/tmp/tmpb3di_03x/"                                                                                                                                     
 AutoGluon Version:  0.4.0                                                                                                                                                             
 Python Version:     3.9.9                                                                                                                                                             
 Operating System:   Linux                                                                                                                                                             
 Train Data Rows:    67968                                                                                                                                                             
 Train Data Columns: 8                                                                                                                                                                 
 Label Column: class                                                                                                                                                                   
 Preprocessing data ...                                                                                                                                                                
 Selected class <--> label mapping:  class 1 = 1, class 0 = 0                                                                                                                          
 Train Data Class Count: 2                                                                                                                                                             
 Using Feature Generators to preprocess the data ...                                                                                                                                   
 Fitting AutoMLPipelineFeatureGenerator...                                                                                                                                             
     Available Memory:                    9338.36 MB                                                                                                                                   
     Train Data (Original)  Memory Usage: 4.35 MB (0.0% of available memory)                                                                                                           
     Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.                                           
     Stage 1 Generators:                                                                                                                                                               
         Fitting AsTypeFeatureGenerator...                                                                                                                                             
     Stage 2 Generators:                                                                                                                                                               
         Fitting FillNaFeatureGenerator...                                                                                                                                             
     Stage 3 Generators:                                                                                                                                                               
         Fitting IdentityFeatureGenerator...                                                                                                                                           
     Stage 4 Generators:                                                                                                                                                               
         Fitting DropUniqueFeatureGenerator...                                                                                                                                         
     Types of features in original data (raw dtype, special dtypes):                                                                                                                   
         ('float', []) : 7 | ['date', 'period', 'nswprice', 'nswdemand', 'vicprice', ...]                                                                                              
         ('int', [])   : 1 | ['day']                                                                                                                                                   
     Types of features in processed data (raw dtype, special dtypes):                                                                                                                  
         ('float', []) : 7 | ['date', 'period', 'nswprice', 'nswdemand', 'vicprice', ...]                                                                                              
         ('int', [])   : 1 | ['day']                                                                                                                                                   
     0.1s = Fit runtime                                                                                                                                                                
     8 features in original data used to generate 8 features in processed data.                                                                                                        
     Train Data (Processed) Memory Usage: 4.35 MB (0.0% of available memory)                                                                                                           
 Data preprocessing and feature engineering runtime = 0.2s ...                                                                                                                         
 AutoGluon will gauge predictive performance using evaluation metric: 'balanced_accuracy'                                                                                              
     To change this, specify the eval_metric parameter of Predictor()                                                                                                                  
 AutoGluon will fit 2 stack levels (L1 to L2) ...                                                                                                                                      
 Excluded Model Types: ['KNN']                                                                                                                                                         
     Found 'KNN' model in hyperparameters, but 'KNN' is present in `excluded_model_types` and will be removed.                                                                         
     Found 'KNN' model in hyperparameters, but 'KNN' is present in `excluded_model_types` and will be removed.                                                                         
 Fitting 11 L1 models ...    
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 119.84s of the 179.8s of remaining time.                                                                                
     Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy                                                                                              
 2022-05-09 06:36:54,038    WARNING services.py:1720 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm 
  performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=0.58gb' to  
 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.                                                    
 2022-05-09 06:38:35,263    WARNING worker.py:1227 -- The autoscaler failed with the following error:                                                                                  
 Traceback (most recent call last):                                                                                                                                                    
   File "/usr/local/lib/python3.9/site-packages/ray/autoscaler/_private/monitor.py", line 331, in run                                                                                  
     self._run()                                                                                                                                                                       
   File "/usr/local/lib/python3.9/site-packages/ray/autoscaler/_private/monitor.py", line 220, in _run                                                                                 
     self.update_load_metrics()                                                                                                                                                        
   File "/usr/local/lib/python3.9/site-packages/ray/autoscaler/_private/monitor.py", line 176, in update_load_metrics                                                                  
     response = self.gcs_node_resources_stub.GetAllResourceUsage(                                                                                                                      
   File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__                                                                                               
     return _end_unary_response_blocking(state, call, False, None)                                                                                                                     
   File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking                                                                           
     raise _InactiveRpcError(state)                                                                                                                                                    
 grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:                                                                                                      
     status = StatusCode.UNAVAILABLE                                                                                                                                                   
     details = "failed to connect to all addresses"                                                                                                                                    
     debug_error_string = "{"created":"@1652078315.254650079","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":315 
 0,"referenced_errors":[{"created":"@1652078315.254648714","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":165,"grpc_sta 
 tus":14}]}" 
```

**To Reproduce**
Training a tabular predictor with [openml 151 dataset](https://www.openml.org/search?type=data&sort=runs&id=151&status=active) causes this issue in our training pod:

```python
from autogluon import tabular
import pandas as pd

df  = pd.read_csv("data.csv")
predictor = tabular.TabularPredictor(
            label="class",
            problem_type="binary",
            path="./model",
            eval_metric="balanced_accuracy",
        )
predictor = predictor.fit(
            train_data=df,
            time_limit=training_config.get(180),
            presets=[
                "high_quality_fast_inference_only_refit",
                "optimize_for_deployment",
            ],
            excluded_model_types=["KNN"],
        )
```
The data file is attached to this bug report: [data.csv](https://github.com/awslabs/autogluon/files/8649737/data.csv)

**Installed Versions**
autogluon 0.4.0

<details>

```python
INSTALLED VERSIONS
------------------
date              : 2022-05-09
time              : 06:56:17.398029
python            : 3.9.9.final.0
OS                : Linux
OS-release        : 5.11.0-1028-aws
Version           : #31~20.04.1-Ubuntu SMP Fri Jan 14 14:37:50 UTC 2022
machine           : x86_64
processor         : 
num_cores         : 8
cpu_ram_mb        : 31753
cuda version      : None
num_gpus          : 0
gpu_ram_mb        : []
avail_disk_size_mb: 513467

autogluon.common  : 0.4.0
autogluon.core    : 0.4.0
autogluon.features: 0.4.0
autogluon.tabular : 0.4.0
boto3             : 1.21.35
catboost          : 1.0.4
dask              : 2021.11.2
distributed       : 2021.11.2
fastai            : 2.5.6
lightgbm          : 3.3.2
matplotlib        : 3.5.1
networkx          : 2.7.1
numpy             : 1.22.3
pandas            : 1.3.5
psutil            : 5.8.0
ray               : 1.7.1
requests          : 2.26.0
scipy             : 1.7.3
sklearn           : 1.0.2
torch             : 1.10.2+cu102
tqdm              : 4.64.0
xgboost           : 1.5.2
```

</details>

**Comment by nilsplettenberg** [comment]
it seems like the issue was due to insufficient memory of the pod
