### ISSUE TITLE
[BUG] AttributeError: module 'google._upb._message' has no attribute 'Message'

### ISSUE THREAD

**Issue by Wang-Lin-boop** [awslabs/autogluon#1725]
**Describe the bug**
After the installation is complete, an error is reported when trying to import AutoGluon.

```
Traceback (most recent call last):
  File "/public/home/wanglin3/DeepShape/DeepShape_Training/training_and_test.py", line 6, in <module>
    from autogluon.text import TextPredictor
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/text/__init__.py", line 1, in <module>
    from . import automm
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/text/automm/__init__.py", line 6, in <module>
    from . import data
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/text/automm/data/__init__.py", line 1, in <module>
    from .datamodule import BaseDataModule
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/text/automm/data/datamodule.py", line 1, in <module>
    from pytorch_lightning import LightningDataModule
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py", line 39, in <module>
    from pytorch_lightning.trainer.connectors.logger_connector.fx_validator import _FxValidator
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/pytorch_lightning/trainer/__init__.py", line 16, in <module>
    from pytorch_lightning.trainer.trainer import Trainer
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 30, in <module>
    from pytorch_lightning.accelerators import Accelerator, IPUAccelerator
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/pytorch_lightning/accelerators/__init__.py", line 13, in <module>
    from pytorch_lightning.accelerators.accelerator import Accelerator  # noqa: F401
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 26, in <module>
    from pytorch_lightning.plugins.precision import ApexMixedPrecisionPlugin, NativeMixedPrecisionPlugin, PrecisionPlugin
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/pytorch_lightning/plugins/__init__.py", line 8, in <module>
    from pytorch_lightning.plugins.plugins_registry import (  # noqa: F401
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/pytorch_lightning/plugins/plugins_registry.py", line 20, in <module>
    from pytorch_lightning.plugins.training_type.training_type_plugin import TrainingTypePlugin
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/__init__.py", line 13, in <module>
    from pytorch_lightning.plugins.training_type.tpu_spawn import TPUSpawnPlugin  # noqa: F401
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py", line 27, in <module>
    from pytorch_lightning.loggers import LoggerCollection, TensorBoardLogger
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/pytorch_lightning/loggers/__init__.py", line 18, in <module>
    from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/pytorch_lightning/loggers/tensorboard.py", line 26, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py", line 13, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/public/home/wanglin3/software/miniconda3/envs/autogluon/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
AttributeError: module 'google._upb._message' has no attribute 'Message'
```
**Installed Versions**
The version used is a beta version 0.4.1b20220503, and I also tested the latest beta version 0.4.1b20220512.
```
Package                 Version
----------------------- --------------
absl-py                 1.0.0
aiohttp                 3.8.1
aiosignal               1.2.0
antlr4-python3-runtime  4.8
async-timeout           4.0.2
attrs                   21.4.0
autocfg                 0.0.8
autogluon               0.4.1b20220503
autogluon.common        0.4.1b20220503
autogluon-contrib-nlp   0.0.1b20220208
autogluon.core          0.4.1b20220503
autogluon.features      0.4.1b20220503
autogluon.tabular       0.4.1b20220503
autogluon.text          0.4.1b20220503
autogluon.vision        0.4.1b20220503
blis                    0.7.7
boto3                   1.22.12
botocore                1.25.12
cachetools              5.0.0
catalogue               2.0.7
catboost                1.0.5
certifi                 2021.10.8
charset-normalizer      2.0.12
click                   8.1.3
cloudpickle             2.0.0
colorama                0.4.4
contextvars             2.4
cycler                  0.11.0
cymem                   2.0.6
dask                    2021.11.2
Deprecated              1.2.13
distributed             2021.11.2
fairscale               0.4.6
fastai                  2.5.6
fastcore                1.4.2
fastdownload            0.0.5
fastprogress            1.0.2
filelock                3.6.0
flake8                  4.0.1
frozenlist              1.3.0
fsspec                  2022.3.0
future                  0.18.2
gluoncv                 0.10.5.post0
google-auth             2.6.6
google-auth-oauthlib    0.4.6
graphviz                0.20
grpcio                  1.46.1
HeapDict                1.0.1
huggingface-hub         0.6.0
idna                    3.3
imageio                 2.19.1
immutables              0.17
importlib-metadata      4.11.3
Jinja2                  3.1.2
jmespath                1.0.0
joblib                  1.1.0
jsonschema              4.5.1
kiwisolver              1.4.2
langcodes               3.3.0
lightgbm                3.3.2
locket                  1.0.0
Markdown                3.3.7
MarkupSafe              2.1.1
matplotlib              3.3.2
mccabe                  0.6.1
msgpack                 1.0.3
multidict               6.0.2
munkres                 1.1.4
murmurhash              1.0.7
networkx                2.8
nptyping                1.4.4
numpy                   1.22.3
oauthlib                3.2.0
omegaconf               2.1.2
opencv-python           4.5.5.64
packaging               21.3
pandas                  1.3.5
partd                   1.2.0
pathy                   0.6.1
Pillow                  9.0.1
pip                     22.0.4
plotly                  5.8.0
portalocker             2.4.0
preshed                 3.0.6
protobuf                4.21.0rc1
psutil                  5.8.0
pyarrow                 8.0.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycodestyle             2.8.0
pydantic                1.8.2
pyDeprecate             0.3.1
pyflakes                2.4.0
pyparsing               3.0.9
pyrsistent              0.18.1
python-dateutil         2.8.2
pytorch-lightning       1.5.10
pytz                    2022.1
PyWavelets              1.3.0
PyYAML                  6.0
ray                     1.10.0
redis                   4.3.1
regex                   2022.4.24
requests                2.27.1
requests-oauthlib       1.3.1
rsa                     4.8
s3transfer              0.5.2
sacrebleu               2.0.0
sacremoses              0.0.53
scikit-image            0.19.2
scikit-learn            1.0.2
scipy                   1.7.3
sentencepiece           0.1.95
setuptools              59.5.0
six                     1.16.0
smart-open              5.2.1
sortedcontainers        2.4.0
spacy                   3.3.0
spacy-legacy            3.0.9
spacy-loggers           1.0.2
srsly                   2.4.3
tabulate                0.8.9
tblib                   1.7.0
tenacity                8.0.1
tensorboard             2.9.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
thinc                   8.0.15
threadpoolctl           3.1.0
tifffile                2022.5.4
timm                    0.5.4
tokenizers              0.12.1
toolz                   0.11.2
torch                   1.10.2+cu113
torchmetrics            0.7.3
torchvision             0.11.3
tornado                 6.1
tqdm                    4.64.0
transformers            4.16.2
typer                   0.4.1
typing_extensions       4.2.0
typish                  1.9.3
urllib3                 1.26.9
wasabi                  0.9.1
Werkzeug                2.1.2
wheel                   0.37.1
wrapt                   1.14.1
xgboost                 1.4.2
yacs                    0.1.8
yarl                    1.7.2
zict                    2.2.0
zipp                    3.8.0
```

**Comment by Wang-Lin-boop** [comment]
In addition, I also tried Python 3.8 and 3.9.

**Comment by Wang-Lin-boop** [comment]
My OS is centos7 on the HPC. In fact, I have successfully installed and run AutoGluon on a local Ubuntu workstation. Could this be related to the operating system?

**Comment by Hassan-Elseoudy** [comment]
Came across this error `google._upb._message` as well but not related to autogluon, I believe it's a GCP error but I don't have a solution yet, did you find any @Wang-Lin-boop?

**Comment by mrgeorge** [comment]
I ran into this error message from another package depending on protobuf via tensorboard. It appears that a recent release of `protobuf                4.21.0rc1` is the culprit, and rolling back to the stable version `protobuf==3.20.1` resolved the issue for me.

**Comment by Wang-Lin-boop** [comment]
@mrgeorge @Hassan-Elseoudy Thank you guys. mrgeorge's answer solved the problem, thanks again!

**Comment by StankovskiA** [comment]
> 

Worked for me, just added protobuf==3.20.1 to requirements.txt

**Comment by Hassan-Elseoudy** [comment]
Tried to add `protobuf="3.20.1"` to My Pipfile and worked correctly!
