### ISSUE TITLE
XGBoost fit error

### ISSUE THREAD

**Issue by wolaiye1010** [awslabs/autogluon#1763]
xgb: 1.6.1

autogluon.tabular: 0.4.1

predictor.fit has error！

Fitting model: NeuralNetFastAI ... Training model for up to 32.2s of the 32.2s of remaining time.
	0.5361	 = Validation score   (roc_auc)
	19.83s	 = Training   runtime
	0.2s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 12.1s of the 12.1s of remaining time.
`eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
	Warning: Exception caused XGBoost to fail during training... Skipping this model.
		2 different `eval_metric` are provided.  Use the one in constructor or `set_params` instead.
Detailed Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/autogluon/core/trainer/abstract_trainer.py", line 1074, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/core/trainer/abstract_trainer.py", line 1032, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 579, in fit
    out = self._fit(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/tabular/models/xgboost/xgboost_model.py", line 136, in _fit
    self.model.fit(
  File "/usr/local/lib/python3.8/dist-packages/xgboost/core.py", line 532, in inner_f
    return f(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/xgboost/sklearn.py", line 1379, in fit
    model, metric, params, early_stopping_rounds, callbacks = self._configure_fit(
  File "/usr/local/lib/python3.8/dist-packages/xgboost/sklearn.py", line 810, in _configure_fit
    _duplicated("eval_metric")
  File "/usr/local/lib/python3.8/dist-packages/xgboost/sklearn.py", line 801, in _duplicated
    raise ValueError(
ValueError: 2 different `eval_metric` are provided.  Use the one in constructor or `set_params` instead.
Fitting model: NeuralNetTorch ... Training model for up to 12.06s of the 12.05s of remaining time.
	Ran out of time, stopping training early. (Stopping on epoch 1)
	0.5633	 = Validation score   (roc_auc)
	12.09s	 = Training   runtime
	0.1s	 = Validation runtime

**Comment by Innixma** [comment]
AutoGluon does not support XGB 1.6.1 in v0.4.1.

Supported versions: `xgboost>=1.4,<1.5`

Please install a supported version of XGBoost and try again.

I've created #1768 to improve the clarity of the pip install instructions.
