### ISSUE TITLE
[BUG] Run error when trying the office tutorial codes...

### ISSUE THREAD

**Issue by lovechang1986** [awslabs/autogluon#1789]
I follow the [Quick start](https://auto.gluon.ai/dev/tutorials/tabular_prediction/tabular-quickstart.html#predicting-columns-in-a-table-quick-start) page to run the office tutorial codes. But something error occured and It's will be fine when I set the `presets=medium_quality` . Please help to sove it...
ps: I run code below on windows 10.

Code below:
```
time_limit = 6660  # for quick demonstration only, you should set this to longest time you are willing to wait (in seconds)
metric = 'roc_auc'  # specify your evaluation metric here
predictor = TabularPredictor(label, eval_metric=metric).fit(train_data, presets='best_quality')
predictor.leaderboard(test_data, silent=True)
```

Error log output:
```
No path specified. Models will be saved in: "AutogluonModels/ag-20220608_053916\"
Presets specified: ['best_quality']
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20220608_053916\"
AutoGluon Version:  0.4.2
Python Version:     3.7.1
Operating System:   Windows
Train Data Rows:    500
Train Data Columns: 14
Label Column: class
Preprocessing data ...
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [' >50K', ' <=50K']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Selected class <--> label mapping:  class 1 =  >50K, class 0 =  <=50K
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive ( >50K) vs negative ( <=50K) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4431.06 MB
	Train Data (Original)  Memory Usage: 0.29 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', [])    : 6 | ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', ...]
		('object', []) : 8 | ['workclass', 'education', 'marital-status', 'occupation', 'relationship', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 7 | ['workclass', 'education', 'marital-status', 'occupation', 'relationship', ...]
		('int', [])       : 6 | ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', ...]
		('int', ['bool']) : 1 | ['sex']
	0.1s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 0.03 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.11s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif_BAG_L1 ...
	0.726	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: KNeighborsDist_BAG_L1 ...
	0.658	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: LightGBMXT_BAG_L1 ...
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy
	Warning: Exception caused LightGBMXT_BAG_L1 to fail during training... Skipping this model.
		can't pickle function objects
Detailed Traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 1074, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 1032, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 579, in fit
    out = self._fit(**kwargs)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\autogluon\core\models\ensemble\stacker_ensemble_model.py", line 153, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\autogluon\core\models\ensemble\bagged_ensemble_model.py", line 234, in _fit
    n_repeats=n_repeats, n_repeat_start=n_repeat_start, save_folds=save_bag_folds, groups=groups, **kwargs)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\autogluon\core\models\ensemble\bagged_ensemble_model.py", line 501, in _fit_folds
    fold_fitting_strategy.schedule_fold_model_fit(**fold_fit_args)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 397, in schedule_fold_model_fit
    self.ray.init(log_to_driver=False)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\ray\worker.py", line 969, in init
    job_config=job_config)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\ray\worker.py", line 1557, in connect
    lambda worker_info: sys.path.insert(1, current_directory))
  File "C:\Users\Administrator\anaconda3\lib\site-packages\ray\worker.py", line 389, in run_function_on_all_workers
    pickled_function = pickle.dumps(function)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\ray\cloudpickle\cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\ray\cloudpickle\cloudpickle_fast.py", line 620, in dump
    return Pickler.dump(self, obj)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\ray\pickle5_files\pickle5\pickle.py", line 485, in dump
    self.save(obj)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\ray\pickle5_files\pickle5\pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\ray\pickle5_files\pickle5\pickle.py", line 689, in save_reduce
    save(func)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\ray\pickle5_files\pickle5\pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\ray\pickle5_files\pickle5\pickle.py", line 689, in save_reduce
    save(func)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\ray\pickle5_files\pickle5\pickle.py", line 576, in save
    rv = reduce(self.proto)
TypeError: can't pickle function objects
Fitting model: LightGBM_BAG_L1 ...
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy
```

**Comment by Innixma** [comment]
Probably fixed in v0.6, please re-open if issue persists in latest release.
