### ISSUE TITLE
'OrderedDict' is not defined in classifier.py

### ISSUE THREAD

**Issue by leo-p** [awslabs/autogluon#194]
Specifying a destination for the `classifier.save()` method results in an error.

```
Traceback (most recent call last):
  File "demo_AutoGluon.py", line 24, in <module>
    classifier.save('saved_model')
  File "xxx/site-packages/autogluon/task/image_classification/classifier.py", line 61, in save
    save(self.state_dict(), checkpoint)
  File "xxx/site-packages/autogluon/task/image_classification/classifier.py", line 51, in state_dict
    destination = OrderedDict()
NameError: name 'OrderedDict' is not defined
```

This seems to be due to the fact that `OrderedDict` is used but never imported in `classifier.py` see here.

This can easily be fixed by adding `from collections import OrderedDict`.

**Comment by Innixma** [comment]
Merged into mainline, thanks for your contribution!
