### ISSUE TITLE
I got an error while running a regression on the house prediction dataset.

### ISSUE THREAD

**Issue by shabir1** [awslabs/autogluon#2096]
I got an error while running a regression on the house prediction dataset. I am using the latest stable version of AutoGluon

AutoGluon Version:  0.5.2
Python Version:     3.9.1
Operating System:   Linux
Train Data Rows:    499
Train Data Columns: 13

I am sharing the logs:
```
Preset alias specified: 'high_quality_fast_inference_only_refit' maps to 'high_quality'.
Presets specified: ['high_quality_fast_inference_only_refit', 'optimize_for_deployment']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 120s
AutoGluon will save models to "/tmp/autogluon//autogluon_model/"
AutoGluon Version:  0.5.2
Python Version:     3.9.1
Operating System:   Linux
Train Data Rows:    499
Train Data Columns: 13
Label Column: price
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    1559.59 MB
	Train Data (Original)  Memory Usage: 0.05 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 13 | ['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 13 | ['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', ...]
	0.0s = Fit runtime
	13 features in original data used to generate 13 features in processed data.
	Train Data (Processed) Memory Usage: 0.05 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.05s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 399, Val Rows: 100
Fitting 8 L1 models ...
Hyperparameter tuning model: LightGBMXT ... Tuning model for up to 13.49s of the 119.95s of remaining time.
[1000]	valid_set's rmse: 2.87221
[1000]	valid_set's rmse: 2.39158
[2000]	valid_set's rmse: 2.31861
[3000]	valid_set's rmse: 2.30775
[1000]	valid_set's rmse: 2.42499
[2000]	valid_set's rmse: 2.36722
[1000]	valid_set's rmse: 2.70433
[2000]	valid_set's rmse: 2.64904
[3000]	valid_set's rmse: 2.63211
[4000]	valid_set's rmse: 2.61721
[5000]	valid_set's rmse: 2.60357
[6000]	valid_set's rmse: 2.59643
[7000]	valid_set's rmse: 2.59869
[8000]	valid_set's rmse: 2.59838
[9000]	valid_set's rmse: 2.59755
[1000]	valid_set's rmse: 2.31411
[1000]	valid_set's rmse: 2.71917
[2000]	valid_set's rmse: 2.66269
[3000]	valid_set's rmse: 2.65319
[4000]	valid_set's rmse: 2.65262
[1000]	valid_set's rmse: 2.42598
[2000]	valid_set's rmse: 2.36472
[3000]	valid_set's rmse: 2.34934
[4000]	valid_set's rmse: 2.36188
[1000]	valid_set's rmse: 2.617
[1000]	valid_set's rmse: 2.75817
[2000]	valid_set's rmse: 2.67996
[3000]	valid_set's rmse: 2.65902
[4000]	valid_set's rmse: 2.64768
[5000]	valid_set's rmse: 2.63984
[6000]	valid_set's rmse: 2.63179
[7000]	valid_set's rmse: 2.62805
[8000]	valid_set's rmse: 2.62751
[9000]	valid_set's rmse: 2.62691
[1000]	valid_set's rmse: 2.39975
[2000]	valid_set's rmse: 2.32847
[3000]	valid_set's rmse: 2.32165
[4000]	valid_set's rmse: 2.32805
[1000]	valid_set's rmse: 2.37653
[2000]	valid_set's rmse: 2.30218
[3000]	valid_set's rmse: 2.28775
	Stopping HPO to satisfy time limit...
Fitted model: LightGBMXT/T1 ...
	-2.3957	 = Validation score   (-root_mean_squared_error)
	0.84s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBMXT/T2 ...
	-2.0984	 = Validation score   (-root_mean_squared_error)
	0.21s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBMXT/T3 ...
	-2.8514	 = Validation score   (-root_mean_squared_error)
	0.24s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBMXT/T4 ...
	-2.3067	 = Validation score   (-root_mean_squared_error)
	0.94s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBMXT/T5 ...
	-2.8614	 = Validation score   (-root_mean_squared_error)
	0.18s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBMXT/T6 ...
	-2.3664	 = Validation score   (-root_mean_squared_error)
	0.73s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBMXT/T7 ...
	-2.848	 = Validation score   (-root_mean_squared_error)
	0.19s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBMXT/T8 ...
	-2.8436	 = Validation score   (-root_mean_squared_error)
	0.23s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBMXT/T9 ...
	-2.5947	 = Validation score   (-root_mean_squared_error)
	1.54s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBMXT/T10 ...
	-2.5698	 = Validation score   (-root_mean_squared_error)
	0.18s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBMXT/T11 ...
	-2.2748	 = Validation score   (-root_mean_squared_error)
	0.47s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBMXT/T12 ...
	-2.65	 = Validation score   (-root_mean_squared_error)
	0.77s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBMXT/T13 ...
	-2.3436	 = Validation score   (-root_mean_squared_error)
	0.92s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBMXT/T14 ...
	-2.5882	 = Validation score   (-root_mean_squared_error)
	0.42s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBMXT/T15 ...
	-2.6243	 = Validation score   (-root_mean_squared_error)
	1.41s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBMXT/T16 ...
	-2.3183	 = Validation score   (-root_mean_squared_error)
	0.98s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBMXT/T17 ...
	-2.2858	 = Validation score   (-root_mean_squared_error)
	0.81s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBMXT/T18 ...
	-2.8636	 = Validation score   (-root_mean_squared_error)
	0.17s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBMXT/T19 ...
	-2.3144	 = Validation score   (-root_mean_squared_error)
	0.21s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBMXT/T20 ...
	-2.3802	 = Validation score   (-root_mean_squared_error)
	0.23s	 = Training   runtime
	0.0s	 = Validation runtime
Hyperparameter tuning model: LightGBM ... Tuning model for up to 13.49s of the 106.55s of remaining time.
[1000]	valid_set's rmse: 2.3145
[1000]	valid_set's rmse: 2.38521
[1000]	valid_set's rmse: 2.59759
[2000]	valid_set's rmse: 2.53785
[3000]	valid_set's rmse: 2.49415
[4000]	valid_set's rmse: 2.45844
[5000]	valid_set's rmse: 2.45853
[6000]	valid_set's rmse: 2.48128
[1000]	valid_set's rmse: 2.64232
[2000]	valid_set's rmse: 2.59484
[3000]	valid_set's rmse: 2.59608
[1000]	valid_set's rmse: 2.3646
[1000]	valid_set's rmse: 2.51709
[1000]	valid_set's rmse: 2.65282
[2000]	valid_set's rmse: 2.5758
[3000]	valid_set's rmse: 2.52399
[4000]	valid_set's rmse: 2.51792
[1000]	valid_set's rmse: 2.27618
[1000]	valid_set's rmse: 2.22947
[1000]	valid_set's rmse: 2.42945
[1000]	valid_set's rmse: 2.90335
[2000]	valid_set's rmse: 2.8701
[1000]	valid_set's rmse: 2.40944
[1000]	valid_set's rmse: 2.45231
[2000]	valid_set's rmse: 2.39422
[3000]	valid_set's rmse: 2.37313
[1000]	valid_set's rmse: 2.87409
	Stopping HPO to satisfy time limit...
Fitted model: LightGBM/T1 ...
	-2.4113	 = Validation score   (-root_mean_squared_error)
	0.22s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T2 ...
	-2.151	 = Validation score   (-root_mean_squared_error)
	0.37s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T3 ...
	-2.8529	 = Validation score   (-root_mean_squared_error)
	0.15s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T4 ...
	-2.3063	 = Validation score   (-root_mean_squared_error)
	0.79s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T5 ...
	-2.823	 = Validation score   (-root_mean_squared_error)
	0.14s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T6 ...
	-2.3795	 = Validation score   (-root_mean_squared_error)
	0.51s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T7 ...
	-2.8309	 = Validation score   (-root_mean_squared_error)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T8 ...
	-2.862	 = Validation score   (-root_mean_squared_error)
	0.12s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T9 ...
	-2.4497	 = Validation score   (-root_mean_squared_error)
	1.22s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T10 ...
	-2.5168	 = Validation score   (-root_mean_squared_error)
	0.16s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T11 ...
	-2.2155	 = Validation score   (-root_mean_squared_error)
	0.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T12 ...
	-2.5832	 = Validation score   (-root_mean_squared_error)
	0.68s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T13 ...
	-2.3618	 = Validation score   (-root_mean_squared_error)
	0.44s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T14 ...
	-2.4975	 = Validation score   (-root_mean_squared_error)
	0.41s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T15 ...
	-2.51	 = Validation score   (-root_mean_squared_error)
	0.97s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T16 ...
	-2.2748	 = Validation score   (-root_mean_squared_error)
	0.48s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T17 ...
	-2.2282	 = Validation score   (-root_mean_squared_error)
	0.55s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T18 ...
	-2.8718	 = Validation score   (-root_mean_squared_error)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T19 ...
	-2.285	 = Validation score   (-root_mean_squared_error)
	0.2s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T20 ...
	-2.2988	 = Validation score   (-root_mean_squared_error)
	0.22s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T21 ...
	-2.2641	 = Validation score   (-root_mean_squared_error)
	0.38s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T22 ...
	-2.3883	 = Validation score   (-root_mean_squared_error)
	0.26s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T23 ...
	-2.8584	 = Validation score   (-root_mean_squared_error)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T24 ...
	-2.6425	 = Validation score   (-root_mean_squared_error)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T25 ...
	-2.8602	 = Validation score   (-root_mean_squared_error)
	0.41s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T26 ...
	-2.242	 = Validation score   (-root_mean_squared_error)
	0.61s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T27 ...
	-2.4015	 = Validation score   (-root_mean_squared_error)
	0.38s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T28 ...
	-2.3659	 = Validation score   (-root_mean_squared_error)
	0.85s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T29 ...
	-2.1768	 = Validation score   (-root_mean_squared_error)
	0.24s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T30 ...
	-2.3029	 = Validation score   (-root_mean_squared_error)
	0.17s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T31 ...
	-2.8369	 = Validation score   (-root_mean_squared_error)
	0.22s	 = Training   runtime
	0.0s	 = Validation runtime
Hyperparameter tuning model: RandomForestMSE ... Tuning model for up to 13.49s of the 92.94s of remaining time.
	No hyperparameter search space specified for RandomForestMSE. Skipping HPO. Will train one model based on the provided hyperparameters.
Model not created {'message': 'Exception occurred while training the model', 'debug_message': 'Exception occurred while creating the DL model Traceback (most recent call last):\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/dengine/tabular/autogluon_tabular_trainer.py", line 220, in train_model\n    self.model.fit(training_df, time_limit=trainingHyperparameters[\'time_limit\'],\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/utils/decorators.py", line 30, in _call\n    return f(*gargs, **gkwargs)\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/tabular/predictor/predictor.py", line 831, in fit\n    self._learner.fit(X=train_data, X_val=tuning_data, X_unlabeled=unlabeled_data,\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/tabular/learner/abstract_learner.py", line 118, in fit\n    return self._fit(X=X, X_val=X_val, **kwargs)\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/tabular/learner/default_learner.py", line 126, in _fit\n    trainer.fit(\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/tabular/trainer/auto_trainer.py", line 85, in fit\n    self._train_multi_and_ensemble(X=X,\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1665, in _train_multi_and_ensemble\n    model_names_fit = self.train_multi_levels(X, y, hyperparameters=hyperparameters, X_val=X_val, y_val=y_val,\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 295, in train_multi_levels\n    base_model_names, aux_models = self.stack_new_level(\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 405, in stack_new_level\n    core_models = self.stack_new_level_core(X=X, y=y, X_val=X_val, y_val=y_val, X_unlabeled=X_unlabeled, models=models,\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 496, in stack_new_level_core\n    return self._train_multi(X=X_init, y=y, X_val=X_val, y_val=y_val, X_unlabeled=X_unlabeled,\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1635, in _train_multi\n    model_names_trained = self._train_multi_initial(X=X, y=y, models=models, k_fold=k_fold, n_repeats=n_repeats_initial, hyperparameter_tune_kwargs=hyperparameter_tune_kwargs,\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1521, in _train_multi_initial\n    models = self._train_multi_fold(models=models, hyperparameter_tune_kwargs=hyperparameter_tune_kwargs,\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1606, in _train_multi_fold\n    model_name_trained_lst = self._train_single_full(X, y, model, time_limit=time_left, hyperparameter_tune_kwargs=hyperparameter_tune_kwargs_model, **kwargs)\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1407, in _train_single_full\n    model_hpo = self.load_model(model_hpo_name, path=model_info[\'path\'], model_type=type(model))\nTypeError: string indices must be integers\n', 'status': 'TRAINING_FAILED'}
Model not created {'message': 'Exception occurred while training the model', 'debug_message': 'Exception occurred while training the model Traceback (most recent call last):\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/dengine/tabular/autogluon_tabular_trainer.py", line 220, in train_model\n    self.model.fit(training_df, time_limit=trainingHyperparameters[\'time_limit\'],\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/utils/decorators.py", line 30, in _call\n    return f(*gargs, **gkwargs)\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/tabular/predictor/predictor.py", line 831, in fit\n    self._learner.fit(X=train_data, X_val=tuning_data, X_unlabeled=unlabeled_data,\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/tabular/learner/abstract_learner.py", line 118, in fit\n    return self._fit(X=X, X_val=X_val, **kwargs)\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/tabular/learner/default_learner.py", line 126, in _fit\n    trainer.fit(\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/tabular/trainer/auto_trainer.py", line 85, in fit\n    self._train_multi_and_ensemble(X=X,\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1665, in _train_multi_and_ensemble\n    model_names_fit = self.train_multi_levels(X, y, hyperparameters=hyperparameters, X_val=X_val, y_val=y_val,\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 295, in train_multi_levels\n    base_model_names, aux_models = self.stack_new_level(\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 405, in stack_new_level\n    core_models = self.stack_new_level_core(X=X, y=y, X_val=X_val, y_val=y_val, X_unlabeled=X_unlabeled, models=models,\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 496, in stack_new_level_core\n    return self._train_multi(X=X_init, y=y, X_val=X_val, y_val=y_val, X_unlabeled=X_unlabeled,\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1635, in _train_multi\n    model_names_trained = self._train_multi_initial(X=X, y=y, models=models, k_fold=k_fold, n_repeats=n_repeats_initial, hyperparameter_tune_kwargs=hyperparameter_tune_kwargs,\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1521, in _train_multi_initial\n    models = self._train_multi_fold(models=models, hyperparameter_tune_kwargs=hyperparameter_tune_kwargs,\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1606, in _train_multi_fold\n    model_name_trained_lst = self._train_single_full(X, y, model, time_limit=time_left, hyperparameter_tune_kwargs=hyperparameter_tune_kwargs_model, **kwargs)\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1407, in _train_single_full\n    model_hpo = self.load_model(model_hpo_name, path=model_info[\'path\'], model_type=type(model))\nTypeError: string indices must be integers\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/dengine/tabular/autogluon_tabular_trainer.py", line 94, in start\n    self.train_model(request_conf[\'trainingHyperparameters\'], training_df)\n  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/dengine/tabular/autogluon_tabular_trainer.py", line 238, in train_model\n    raise Exception("Model not created")\nException: Model not created\n', 'status': 'TRAINING_FAILED'}
Traceback (most recent call last):
  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/dengine/tabular/autogluon_tabular_trainer.py", line 220, in train_model
    self.model.fit(training_df, time_limit=trainingHyperparameters['time_limit'],
  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/utils/decorators.py", line 30, in _call
    return f(*gargs, **gkwargs)
  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/tabular/predictor/predictor.py", line 831, in fit
    self._learner.fit(X=train_data, X_val=tuning_data, X_unlabeled=unlabeled_data,
  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/tabular/learner/abstract_learner.py", line 118, in fit
    return self._fit(X=X, X_val=X_val, **kwargs)
  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/tabular/learner/default_learner.py", line 126, in _fit
    trainer.fit(
  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/tabular/trainer/auto_trainer.py", line 85, in fit
    self._train_multi_and_ensemble(X=X,
  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1665, in _train_multi_and_ensemble
    model_names_fit = self.train_multi_levels(X, y, hyperparameters=hyperparameters, X_val=X_val, y_val=y_val,
  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 295, in train_multi_levels
    base_model_names, aux_models = self.stack_new_level(
  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 405, in stack_new_level
    core_models = self.stack_new_level_core(X=X, y=y, X_val=X_val, y_val=y_val, X_unlabeled=X_unlabeled, models=models,
  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 496, in stack_new_level_core
    return self._train_multi(X=X_init, y=y, X_val=X_val, y_val=y_val, X_unlabeled=X_unlabeled,
  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1635, in _train_multi
    model_names_trained = self._train_multi_initial(X=X, y=y, models=models, k_fold=k_fold, n_repeats=n_repeats_initial, hyperparameter_tune_kwargs=hyperparameter_tune_kwargs,
  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1521, in _train_multi_initial
    models = self._train_multi_fold(models=models, hyperparameter_tune_kwargs=hyperparameter_tune_kwargs,
  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1606, in _train_multi_fold
    model_name_trained_lst = self._train_single_full(X, y, model, time_limit=time_left, hyperparameter_tune_kwargs=hyperparameter_tune_kwargs_model, **kwargs)
  File "/home/shabir/work/datoinmodules/mlmodules/automl-frameworks/datoin-autogluon-framework/.vir/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1407, in _train_single_full
    model_hpo = self.load_model(model_hpo_name, path=model_info['path'], model_type=type(model))
TypeError: string indices must be integers
```

**Comment by Innixma** [comment]
Thanks for reporting! This bug has been fixed in https://github.com/awslabs/autogluon/pull/2070 , however is not yet part of a release. You can get the fix by installing the pre-release or building from source.
