### ISSUE TITLE
[BUG] Interpretable Model Fit fails with "object has no attribute '_ohe'" when no categorical features provided

### ISSUE THREAD

**Issue by garvijayaud** [awslabs/autogluon#2107]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [x] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
2 issues: 
* imodels not installed when following the documented installation procedure
* after manually installing imodels, fitting fails with ```object has no attribute '_ohe'``` when fitted on a dataset with no categorical features.

**Expected behavior**
imodels should be installed when following the documented installation procedure, and model fitting should work when purely numerical data is provided.

**To Reproduce**
Installed on a sagemaker notebook instance as follows:
```
uname -a
# Linux ip-xxxxxx 4.14.252-131.483.amzn1.x86_64 #1 SMP Mon Nov 1 20:48:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
conda create -p /home/ec2-user/SageMaker/envs/autogluon python=3.9
conda activate autogluon
pip3 install -U pip
pip3 install -U setuptools wheel
pip3 install torch==1.12+cpu torchvision==0.13.0+cpu torchtext==0.13.0 -f https://download.pytorch.org/whl/cpu/torch_stable.html
pip3 install autogluon
pip3 list | grep autogluon
# autogluon                       0.5.2
# autogluon.common                0.5.2
# autogluon-contrib-nlp           0.0.1b20220208
# autogluon.core                  0.5.2
# autogluon.features              0.5.2
# autogluon.multimodal            0.5.2
# autogluon.tabular               0.5.2
# autogluon.text                  0.5.2
# autogluon.timeseries            0.5.2
# autogluon.vision                0.5.2
pip3 list | grep imodels
# no imodels! manually install
pip3 install -U imodels>=1.3.0
# imodels                 1.3.4
```

The standard example works fine:
```bash
from autogluon.tabular import TabularDataset, TabularPredictor
train_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
subsample_size = 500  # subsample subset of data for faster demo, try setting this to much larger values
train_data = train_data.sample(n=subsample_size, random_state=0)
predictor = TabularPredictor(label='class')
predictor.fit(train_data, presets='interpretable')
predictor.leaderboard()
```

But selecting just a few numeric features for training causes an error, code:
```python
train_data2 = train_data.loc[:, ['age', 'fnlwgt', 'hours-per-week', 'class']]
predictor = TabularPredictor(label='class')
predictor.fit(train_data2, presets='interpretable')
predictor.leaderboard()
```

output:
```
No path specified. Models will be saved in: "AutogluonModels/ag-20220905_144131/"
Presets specified: ['interpretable']
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20220905_144131/"
AutoGluon Version:  0.5.2
Python Version:     3.9.13
Operating System:   Linux
Train Data Rows:    500
Train Data Columns: 3
Label Column: class
Preprocessing data ...
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [' >50K', ' <=50K']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Selected class <--> label mapping:  class 1 =  >50K, class 0 =  <=50K
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive ( >50K) vs negative ( <=50K) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    14753.23 MB
	Train Data (Original)  Memory Usage: 0.01 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 3 | ['age', 'fnlwgt', 'hours-per-week']
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 3 | ['age', 'fnlwgt', 'hours-per-week']
	0.0s = Fit runtime
	3 features in original data used to generate 3 features in processed data.
	Train Data (Processed) Memory Usage: 0.01 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.03s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 400, Val Rows: 100
Fitting 12 L1 models ...
Fitting model: RuleFit ...
	Warning: Exception caused RuleFit to fail during training... Skipping this model.
		'RuleFitModel' object has no attribute '_ohe'
Detailed Traceback:
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1126, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1083, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 587, in fit
    out = self._fit(**kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 52, in _fit
    X = self.preprocess(X, is_train=True)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 308, in preprocess
    X = self._preprocess(X, **kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 35, in _preprocess
    if self._ohe is not None:
AttributeError: 'RuleFitModel' object has no attribute '_ohe'
Fitting model: RuleFit_2 ...
	Warning: Exception caused RuleFit_2 to fail during training... Skipping this model.
		'RuleFitModel' object has no attribute '_ohe'
Detailed Traceback:
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1126, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1083, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 587, in fit
    out = self._fit(**kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 52, in _fit
    X = self.preprocess(X, is_train=True)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 308, in preprocess
    X = self._preprocess(X, **kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 35, in _preprocess
    if self._ohe is not None:
AttributeError: 'RuleFitModel' object has no attribute '_ohe'
Fitting model: RuleFit_3 ...
	Warning: Exception caused RuleFit_3 to fail during training... Skipping this model.
		'RuleFitModel' object has no attribute '_ohe'
Detailed Traceback:
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1126, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1083, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 587, in fit
    out = self._fit(**kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 52, in _fit
    X = self.preprocess(X, is_train=True)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 308, in preprocess
    X = self._preprocess(X, **kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 35, in _preprocess
    if self._ohe is not None:
AttributeError: 'RuleFitModel' object has no attribute '_ohe'
Fitting model: GreedyTree ...
	Warning: Exception caused GreedyTree to fail during training... Skipping this model.
		'GreedyTreeModel' object has no attribute '_ohe'
Detailed Traceback:
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1126, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1083, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 587, in fit
    out = self._fit(**kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 52, in _fit
    X = self.preprocess(X, is_train=True)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 308, in preprocess
    X = self._preprocess(X, **kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 35, in _preprocess
    if self._ohe is not None:
AttributeError: 'GreedyTreeModel' object has no attribute '_ohe'

Fitting model: BoostedRules ...
	Warning: Exception caused BoostedRules to fail during training... Skipping this model.
		'BoostedRulesModel' object has no attribute '_ohe'
Detailed Traceback:
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1126, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1083, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 587, in fit
    out = self._fit(**kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 52, in _fit
    X = self.preprocess(X, is_train=True)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 308, in preprocess
    X = self._preprocess(X, **kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 35, in _preprocess
    if self._ohe is not None:
AttributeError: 'BoostedRulesModel' object has no attribute '_ohe'
Fitting model: BoostedRules_2 ...
	Warning: Exception caused BoostedRules_2 to fail during training... Skipping this model.
		'BoostedRulesModel' object has no attribute '_ohe'
Detailed Traceback:
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1126, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1083, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 587, in fit
    out = self._fit(**kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 52, in _fit
    X = self.preprocess(X, is_train=True)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 308, in preprocess
    X = self._preprocess(X, **kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 35, in _preprocess
    if self._ohe is not None:
AttributeError: 'BoostedRulesModel' object has no attribute '_ohe'
Fitting model: Figs ...
	Warning: Exception caused Figs to fail during training... Skipping this model.
		'FigsModel' object has no attribute '_ohe'
Detailed Traceback:
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1126, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1083, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 587, in fit
    out = self._fit(**kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 52, in _fit
    X = self.preprocess(X, is_train=True)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 308, in preprocess
    X = self._preprocess(X, **kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 35, in _preprocess
    if self._ohe is not None:
AttributeError: 'FigsModel' object has no attribute '_ohe'
Fitting model: Figs_2 ...
	Warning: Exception caused Figs_2 to fail during training... Skipping this model.
		'FigsModel' object has no attribute '_ohe'
Detailed Traceback:
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1126, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1083, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 587, in fit
    out = self._fit(**kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 52, in _fit
    X = self.preprocess(X, is_train=True)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 308, in preprocess
    X = self._preprocess(X, **kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 35, in _preprocess
    if self._ohe is not None:
AttributeError: 'FigsModel' object has no attribute '_ohe'
Fitting model: Figs_3 ...
	Warning: Exception caused Figs_3 to fail during training... Skipping this model.
		'FigsModel' object has no attribute '_ohe'
Detailed Traceback:
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1126, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1083, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 587, in fit
    out = self._fit(**kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 52, in _fit
    X = self.preprocess(X, is_train=True)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 308, in preprocess
    X = self._preprocess(X, **kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 35, in _preprocess
    if self._ohe is not None:
AttributeError: 'FigsModel' object has no attribute '_ohe'
Fitting model: HierarchicalShrinkageTree ...
	Warning: Exception caused HierarchicalShrinkageTree to fail during training... Skipping this model.
		'HSTreeModel' object has no attribute '_ohe'
Detailed Traceback:
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1126, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1083, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 587, in fit
    out = self._fit(**kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 52, in _fit
    X = self.preprocess(X, is_train=True)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 308, in preprocess
    X = self._preprocess(X, **kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 35, in _preprocess
    if self._ohe is not None:
AttributeError: 'HSTreeModel' object has no attribute '_ohe'

Fitting model: HierarchicalShrinkageTree_2 ...
	Warning: Exception caused HierarchicalShrinkageTree_2 to fail during training... Skipping this model.
		'HSTreeModel' object has no attribute '_ohe'
Detailed Traceback:
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1126, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1083, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 587, in fit
    out = self._fit(**kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 52, in _fit
    X = self.preprocess(X, is_train=True)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 308, in preprocess
    X = self._preprocess(X, **kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 35, in _preprocess
    if self._ohe is not None:
AttributeError: 'HSTreeModel' object has no attribute '_ohe'
Fitting model: HierarchicalShrinkageTree_3 ...
	Warning: Exception caused HierarchicalShrinkageTree_3 to fail during training... Skipping this model.
		'HSTreeModel' object has no attribute '_ohe'
Detailed Traceback:
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1126, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1083, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 587, in fit
    out = self._fit(**kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 52, in _fit
    X = self.preprocess(X, is_train=True)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 308, in preprocess
    X = self._preprocess(X, **kwargs)
  File "/home/ec2-user/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/imodels/imodels_models.py", line 35, in _preprocess
    if self._ohe is not None:
AttributeError: 'HSTreeModel' object has no attribute '_ohe'
No base models to train on, skipping auxiliary stack level 2...

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [5], in <cell line: 2>()
      1 predictor = TabularPredictor(label='class')
----> 2 predictor.fit(train_data2, presets='interpretable')
      3 predictor.leaderboard()

File ~/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/utils/decorators.py:30, in unpack.<locals>._unpack_inner.<locals>._call(*args, **kwargs)
     27 @functools.wraps(f)
     28 def _call(*args, **kwargs):
     29     gargs, gkwargs = g(*other_args, *args, **kwargs)
---> 30     return f(*gargs, **gkwargs)

File ~/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/predictor/predictor.py:831, in TabularPredictor.fit(self, train_data, tuning_data, time_limit, presets, hyperparameters, feature_metadata, infer_limit, infer_limit_batch_size, **kwargs)
    823 core_kwargs = {
    824     'ag_args': ag_args,
    825     'ag_args_ensemble': ag_args_ensemble,
   (...)
    828     'feature_prune_kwargs': kwargs.get('feature_prune_kwargs', None)
    829 }
    830 self.save(silent=True)  # Save predictor to disk to enable prediction and training after interrupt
--> 831 self._learner.fit(X=train_data, X_val=tuning_data, X_unlabeled=unlabeled_data,
    832                   holdout_frac=holdout_frac, num_bag_folds=num_bag_folds, num_bag_sets=num_bag_sets,
    833                   num_stack_levels=num_stack_levels,
    834                   hyperparameters=hyperparameters, core_kwargs=core_kwargs,
    835                   time_limit=time_limit, infer_limit=infer_limit, infer_limit_batch_size=infer_limit_batch_size,
    836                   verbosity=verbosity, use_bag_holdout=use_bag_holdout)
    837 self._set_post_fit_vars()
    839 self._post_fit(
    840     keep_only_best=kwargs['keep_only_best'],
    841     refit_full=kwargs['refit_full'],
   (...)
    845     infer_limit=infer_limit,
    846 )

File ~/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/learner/abstract_learner.py:118, in AbstractTabularLearner.fit(self, X, X_val, **kwargs)
    116     raise AssertionError('Learner is already fit.')
    117 self._validate_fit_input(X=X, X_val=X_val, **kwargs)
--> 118 return self._fit(X=X, X_val=X_val, **kwargs)

File ~/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/learner/default_learner.py:126, in DefaultLearner._fit(self, X, X_val, X_unlabeled, holdout_frac, num_bag_folds, num_bag_sets, time_limit, infer_limit, infer_limit_batch_size, verbosity, **trainer_fit_kwargs)
    123     self.eval_metric = trainer.eval_metric
    125 self.save()
--> 126 trainer.fit(
    127     X=X,
    128     y=y,
    129     X_val=X_val,
    130     y_val=y_val,
    131     X_unlabeled=X_unlabeled,
    132     holdout_frac=holdout_frac,
    133     time_limit=time_limit_trainer,
    134     infer_limit=infer_limit,
    135     infer_limit_batch_size=infer_limit_batch_size,
    136     groups=groups,
    137     **trainer_fit_kwargs
    138 )
    139 self.save_trainer(trainer=trainer)
    140 time_end = time.time()

File ~/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/trainer/auto_trainer.py:85, in AutoTrainer.fit(self, X, y, hyperparameters, X_val, y_val, X_unlabeled, holdout_frac, num_stack_levels, core_kwargs, time_limit, infer_limit, infer_limit_batch_size, use_bag_holdout, groups, **kwargs)
     76     if not use_bag_holdout:
     77         # TODO: User could be intending to blend instead. Add support for blend stacking.
     78         #  This error message is necessary because when calculating out-of-fold predictions for user, we want to return them in the form given in train_data,
     79         #  but if we merge train and val here, it becomes very confusing from a users perspective, especially because we reset index, making it impossible to match
     80         #  the original train_data to the out-of-fold predictions from `predictor.get_oof_pred_proba()`.
     81         raise AssertionError('X_val, y_val is not None, but bagged mode was specified. If calling from `TabularPredictor.fit()`, `tuning_data` must be None.\n'
     82                              'Bagged mode does not use tuning data / validation data. Instead, all data (`train_data` and `tuning_data`) should be combined and specified as `train_data`.\n'
     83                              'Bagging/Stacking with a held-out validation set (blend stacking) is not yet supported.')
---> 85 self._train_multi_and_ensemble(X=X,
     86                                y=y,
     87                                X_val=X_val,
     88                                y_val=y_val,
     89                                X_unlabeled=X_unlabeled,
     90                                hyperparameters=hyperparameters,
     91                                num_stack_levels=num_stack_levels,
     92                                time_limit=time_limit,
     93                                core_kwargs=core_kwargs,
     94                                infer_limit=infer_limit,
     95                                infer_limit_batch_size=infer_limit_batch_size,
     96                                groups=groups)

File ~/SageMaker/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py:1668, in AbstractTrainer._train_multi_and_ensemble(self, X, y, X_val, y_val, hyperparameters, X_unlabeled, num_stack_levels, time_limit, groups, **kwargs)
   1665 model_names_fit = self.train_multi_levels(X, y, hyperparameters=hyperparameters, X_val=X_val, y_val=y_val,
   1666                                           X_unlabeled=X_unlabeled, level_start=1, level_end=num_stack_levels+1, time_limit=time_limit, **kwargs)
   1667 if len(self.get_model_names()) == 0:
-> 1668     raise ValueError('AutoGluon did not successfully train any models')
   1669 return model_names_fit

ValueError: AutoGluon did not successfully train any models
```

**Installed Versions**
Which version of AutoGluon are you are using?  0.5.2

```python
INSTALLED VERSIONS
------------------
date                   : 2022-09-05
time                   : 14:51:27.591216
python                 : 3.9.13.final.0
OS                     : Linux
OS-release             : 4.14.252-131.483.amzn1.x86_64
Version                : #1 SMP Mon Nov 1 20:48:11 UTC 2021
machine                : x86_64
processor              : x86_64
num_cores              : 4
cpu_ram_mb             : 15746
cuda version           : None
num_gpus               : 0
gpu_ram_mb             : []
avail_disk_size_mb     : 448600

autogluon.common       : 0.5.2
autogluon.core         : 0.5.2
autogluon.features     : 0.5.2
autogluon.multimodal   : 0.5.2
autogluon.tabular      : 0.5.2
autogluon.text         : 0.5.2
autogluon.timeseries   : None
autogluon.vision       : 0.5.2
autogluon_contrib_nlp  : None
boto3                  : 1.24.66
catboost               : 1.0.6
dask                   : 2021.11.2
distributed            : 2021.11.2
fairscale              : 0.4.6
fastai                 : 2.7.9
gluoncv                : 0.11.0
hyperopt               : 0.2.7
lightgbm               : 3.3.2
matplotlib             : 3.5.3
networkx               : 2.8.6
nlpaug                 : 1.1.10
nltk                   : 3.7
nptyping               : 1.4.4
numpy                  : 1.21.6
omegaconf              : 2.1.2
pandas                 : 1.4.4
PIL                    : 9.0.1
protobuf               : None
psutil                 : 5.8.0
pytorch-metric-learning: None
pytorch_lightning      : 1.6.5
ray                    : 1.13.0
requests               : 2.28.1
scipy                  : 1.7.3
sentencepiece          : None
skimage                : 0.19.3
sklearn                : 1.0.2
smart_open             : 5.2.1
timm                   : 0.5.4
torch                  : 1.12.0+cpu
torchmetrics           : 0.7.3
torchtext              : 0.13.0
torchvision            : 0.13.0+cpu
tqdm                   : 4.64.1
transformers           : 4.20.1
xgboost                : 1.4.2
```

</details>

**Additional context**

**Comment by nimasteryang** [comment]
Same issues here.

**Comment by Zagonair** [comment]
Same problem, since I needed it and din't want to wait I fixed it just by adding the line 
`self._ohe = None`
within the __init__ function inside <python installation path>/dist-packages/autogluon/tabular/models/imodels/imodels_models.py

**Comment by Innixma** [comment]
Thanks @garvijayaud for creating this issue, and thanks @Zagonair for mentioning a solution!

I have created a PR to fix this bug: #2178

Once merged, the fix should be available in v0.6 release or sooner via source install / nightly pre-release.

**Comment by garvijayaud** [comment]
thank you!

**Comment by Innixma** [comment]
PR is merged and the issue should be fixed
