### ISSUE TITLE
why I get error when I run my code?

### ISSUE THREAD

**Issue by yllgl** [awslabs/autogluon#213]
I write my code as follows:

[autotrain.txt](https://github.com/awslabs/autogluon/files/4063315/autotrain.txt)
but when I run my code on linux，I get this error as follows. Could you help me solve it?
> Traceback (most recent call last):
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 38, in dumps
    result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
_pickle.PicklingError: Can't pickle <function ag_train_mnist at 0x7f582b8bb7a0>: it's not the same object as __main__.ag_train_mnist
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "autotrain.py", line 287, in <module>
    myscheduler.run()
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/autogluon/scheduler/fifo.py", line 146, in run
    self.schedule_next()
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/autogluon/scheduler/fifo.py", line 177, in schedule_next
    self.add_job(task, **extra_kwargs)
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/autogluon/scheduler/fifo.py", line 223, in add_job
    job = cls._start_distributed_job(task, cls.RESOURCE_MANAGER, self.env_sem)
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/autogluon/scheduler/scheduler.py", line 102, in _start_distributed_job
    env_sem)
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/distributed/client.py", line 1501, in submit
    actors=actor,
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/distributed/client.py", line 2492, in _graph_to_futures
    "tasks": valmap(dumps_task, dsk3),
  File "cytoolz/dicttoolz.pyx", line 179, in cytoolz.dicttoolz.valmap
  File "cytoolz/dicttoolz.pyx", line 204, in cytoolz.dicttoolz.valmap
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 3282, in dumps_task
    return {"function": dumps_function(task[0]), "args": warn_dumps(task[1:])}
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 3291, in warn_dumps
    b = dumps(obj)
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 51, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 1125, in dumps
    cp.dump(obj)
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 482, in dump
    return Pickler.dump(self, obj)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 556, in save_function
    return self.save_function_tuple(obj)
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 758, in save_function_tuple
    save(state)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 890, in _batch_setitems
    save(v)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 556, in save_function
    return self.save_function_tuple(obj)
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 758, in save_function_tuple
    save(state)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 890, in _batch_setitems
    save(v)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 556, in save_function
    return self.save_function_tuple(obj)
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 758, in save_function_tuple
    save(state)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(x)
  File "/home/yllgl/anaconda3/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
TypeError: can't pickle CudnnModule objects

**Comment by zhanghang1989** [comment]
Looks like your function / object can not be serialized by pickle.

**Comment by yaojunr** [comment]
I use pytorch as backend. I also meet the same problem. If the problem occurs, how i can deal with it? Or how i can know which variable cause the problem.  My train script seems the same as the code provided in 'MNIST Training in PyTorch' tutorial.

**Comment by zhanghang1989** [comment]
@yllgl Sorry for the delay. Didn't notice that you have attached the code.

The dataset/dataloader should be created inside the training function or being created through `@ag.obj()` or `@ag.func()` https://autogluon.mxnet.io/api/autogluon.core.html?highlight=func#autogluon.func  then pass through the `@ag.args()`.

**Comment by zhanghang1989** [comment]
@yaojunr Please see my reply to @yllgl . Let me know if you have resolved that.

**Comment by Innixma** [comment]
Resolving, please re-open if issues still persist.
