### ISSUE TITLE
NAS：search_efficientnet.py demo Error

### ISSUE THREAD

**Issue by enduringstack** [awslabs/autogluon#214]
TraceBack:

AttributeError: module 'autogluon' has no attribute 'nas'

**Comment by zhanghang1989** [comment]
Could you change `nas` to `model_zoo`?

**Comment by enduringstack** [comment]
@zhanghang1989  Change `nas` to `model_zoo`  can not solve the issue.

I have a try of the following modify:

- add code
```python
from autogluon import model_zoo as mz
```

- change `nas`  to `mz.models`

however, new problem arise:
```
ssh://root@10.143.196.175:19975/usr/bin/python -u /root/autogluon/NAS/enas_proxylessnas/search_efficientnet.py
Starting Experiments
Num of Finished Tasks is 0
Num of Pending Tasks is 2
  0%|                                                     | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/autogluon/NAS/enas_proxylessnas/search_efficientnet.py", line 25, in <module>
    batch_size=32)
  File "/usr/bin/python36/lib/python3.6/site-packages/autogluon/task/image_classification/image_classification.py", line 166, in fit
    scheduler_options)
  File "/usr/bin/python36/lib/python3.6/site-packages/autogluon/task/base/base_task.py", line 42, in run_fit
    scheduler.run()
  File "/usr/bin/python36/lib/python3.6/site-packages/autogluon/scheduler/fifo.py", line 146, in run
    self.schedule_next()
  File "/usr/bin/python36/lib/python3.6/site-packages/autogluon/scheduler/fifo.py", line 170, in schedule_next
    config = self.searcher.get_config(**extra_kwargs)
  File "/usr/bin/python36/lib/python3.6/site-packages/autogluon/searcher/searcher.py", line 159, in get_config
    self.MAX_RETRIES)
AssertionError: Cannot find new config in BaseSearcher, even after 100 trials
Process Process-2:
Traceback (most recent call last):
  File "/usr/bin/python36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/bin/python36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/python36/lib/python3.6/site-packages/autogluon/scheduler/scheduler.py", line 125, in _worker
    ret = fn(**kwargs)
  File "/usr/bin/python36/lib/python3.6/site-packages/autogluon/core/decorator.py", line 58, in __call__
    output = self.f(args, **kwargs)
  File "/usr/bin/python36/lib/python3.6/site-packages/autogluon/core/decorator.py", line 138, in wrapper_call
    return func(*args, **kwargs)
  File "/usr/bin/python36/lib/python3.6/site-packages/autogluon/task/image_classification/pipeline.py", line 38, in train_image_classification
    net = get_network(args.net, num_classes, ctx)
  File "/usr/bin/python36/lib/python3.6/site-packages/autogluon/task/image_classification/nets.py", line 83, in get_network
    net.initialize(ctx=ctx)
AttributeError: 'NoneType' object has no attribute 'initialize'
```

tks.
