### ISSUE TITLE
Autogluon Tabular Predictor: IndexError: list index out of range

### ISSUE THREAD

**Issue by hkaurut** [awslabs/autogluon#2208]
Hi , I am using Autogluon Tabular predictor. The predictor is as follows:
predictor= TabularPredictor(
    label="ops",
    verbosity=4,
    problem_type="regression",
    path="agModels-predicttest1”,
    eval_metric='mean_absolute_error'
  ).fit(
    train_data=train_data_transformed.drop(
      ["spotcp", "ad_revenue", "pb_ops", "pb_spotcp"], axis=1),
    feature_generator=IdentityFeatureGenerator(),
    time_limit=3200,
    # visualizer='tensorboard',
    presets='medium_quality',   #'optimize_for_deployment', #'best_quality',
    hyperparameters={"GBM":{'num_boost_round': [ag.space.Int](http://ag.space.int/)(lower=50, upper=2000, default=100),
    'num_leaves': [ag.space.Int](http://ag.space.int/)(lower=64, upper=1024, default=256),
    'learning_rate': ag.space.Real(3e-2, 2e-1, default=1e-1,log=True),
    'max_depth':[ag.space.Int](http://ag.space.int/)(lower=6, upper=10, default=8),
    'early_stopping_round':10,'min_data_in_leaf': [ag.space.Int](http://ag.space.int/)(lower=10, upper=100, default=20)}},
    hyperparameter_tune_kwargs={'num_trials': 10,'searcher': 'auto','scheduler':'local'}
  )
With medium_quality presets and hyper parameter tuning, if I try to load the model after training as follows:
predictor_test1=TabularPredictor.load("/home/hadoop/agModels-predicttest1/“)
I get the following error:
Traceback (most recent call last):
 File "/tmp/1665687139040-0/zeppelin_python.py", line 158, in <module>
  exec(code, _zcUserQueryNameSpace)
 File "<stdin>", line 7, in <module>
 File "/usr/local/lib/python3.7/site-packages/autogluon/tabular/predictor/predictor.py", line 2901, in load
  predictor = cls._load(path=path)
 File "/usr/local/lib/python3.7/site-packages/autogluon/tabular/predictor/predictor.py", line 2833, in _load
  predictor._set_post_fit_vars(learner=learner)
 File "/usr/local/lib/python3.7/site-packages/autogluon/tabular/predictor/predictor.py", line 2787, in _set_post_fit_vars
  self._learner.persist_trainer(low_memory=True)
 File "/usr/local/lib/python3.7/site-packages/autogluon/tabular/learner/abstract_learner.py", line 704, in persist_trainer
  self.trainer = self.load_trainer()
 File "/usr/local/lib/python3.7/site-packages/autogluon/core/learner/abstract_learner.py", line 121, in load_trainer
  path=self.trainer_path, reset_paths=self.reset_paths
 File "/usr/local/lib/python3.7/site-packages/autogluon/core/trainer/abstract_trainer.py", line 2315, in load
  obj.set_contexts(path)
 File "/usr/local/lib/python3.7/site-packages/autogluon/core/trainer/abstract_trainer.py", line 214, in set_contexts
  self.path, model_paths = self.create_contexts(path_context)
 File "/usr/local/lib/python3.7/site-packages/autogluon/core/trainer/abstract_trainer.py", line 224, in create_contexts
  model_local_path = prev_path.split(abs_path, 1)[1]
IndexError: list index out of range
However, it works fine if I use presets=Best_quality where auto_stack=True. I am not sure why medium_quality Presets with hyperparameter tuning are giving this error at the time of loading the weights.

**Comment by Innixma** [comment]
You are doing some pretty advanced things here without providing the original data / code, so it is hard to assist. Please provide a reproducible example on Colab so we can help.

**Comment by Alex-Wenner-FHR** [comment]
```python
  File "ag_pipeline.py", line 86, in <module>
    score = agp.inference_models()
  File "ag_pipeline.py", line 64, in inference_models
    predictor = TabularPredictor.load(file, require_version_match=False, verbosity=4)
  File "/Users/alexw/Developer/PythonEnvs/py3.8/lib/python3.8/site-packages/autogluon/tabular/predictor/predictor.py", line 3047, in load
    predictor = cls._load(path=path)
  File "/Users/alexw/Developer/PythonEnvs/py3.8/lib/python3.8/site-packages/autogluon/tabular/predictor/predictor.py", line 2950, in _load
    predictor._set_post_fit_vars(learner=learner)
  File "/Users/alexw/Developer/PythonEnvs/py3.8/lib/python3.8/site-packages/autogluon/tabular/predictor/predictor.py", line 2882, in _set_post_fit_vars
    self._learner.persist_trainer(low_memory=True)
  File "/Users/alexw/Developer/PythonEnvs/py3.8/lib/python3.8/site-packages/autogluon/tabular/learner/abstract_learner.py", line 707, in persist_trainer
    self.trainer = self.load_trainer()
  File "/Users/alexw/Developer/PythonEnvs/py3.8/lib/python3.8/site-packages/autogluon/core/learner/abstract_learner.py", line 120, in load_trainer
    return self.trainer_type.load(  # noqa
  File "/Users/alexw/Developer/PythonEnvs/py3.8/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py", line 2603, in load
    obj.set_contexts(path)
  File "/Users/alexw/Developer/PythonEnvs/py3.8/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py", line 219, in set_contexts
    self.path, model_paths = self.create_contexts(path_context)
  File "/Users/alexw/Developer/PythonEnvs/py3.8/lib/python3.8/site-packages/autogluon/core/trainer/abstract_trainer.py", line 229, in create_contexts
    model_local_path = prev_path.split(abs_path, 1)[1]
IndexError: list index out of range
````


@Innixma I am also seeing this with version 0.6.1. Going to try to upgrade to 0.6.2 but wanted to get the issue out there.

Our models were trained locally and the model folders (artifacts) were zipped up and pushed to the cloud. When being read in by a separate process (both running python 3.8 & autogluon 0.6.1) we see this issue. The only difference that I can evidently see is that the machine pulling the models into memory was Darwin and they were trained on Windows.

```python
TabularPredictor.load(filname)
```  
Seems to be what causes this error.


When printing out the `abs_path` in the code block above provided by @rsj123 , it appears to be tied to the training machine and its FS and not the current location. See below:

`/Users/alexw/Developer/Folder1/Folder2/Folder3/src/code/C:\Users\OtherUser\OneDrive\Desktop\Platform\Test\Outside\models\/` as where I would expect it to be `./Outside/models` (omitted actual path values)

**Comment by Alex-Wenner-FHR** [comment]
Update: Also confirmed the same problem with training done on `0.6.2` and inferencing done on `0.6.2`.

**Comment by Alex-Wenner-FHR** [comment]
Update: I believe I have confirmed this to be an issue with Windows training -> Mac inferencing. I reproduced the model on Darwin and also inferenced on Darwin and no issue appears to be present.

**Comment by Innixma** [comment]
Thanks for providing the additional information @Alex-Wenner-FHR and @rsj123. I have this on my radar and will see if it can be fixed for the upcoming v0.7 release

**Comment by sayebmsibx** [comment]
I have the same issue. Both training and inference are done in google vertex ai notebooks. when I zip the model folder and upload it to the bucket it can't be used by anyone else becaue of this issue.

**Comment by Innixma** [comment]
I identified and confirmed the bug.

The following PR should fix the issue: #2865 

However, as properly confirming that this fixes the problem requires both a Windows and MacOS/Linux machine, I might need your help to confirm that this does fix the problem.

@sayebmsibx @Alex-Wenner-FHR @rsj123 If you could try to create a fresh python environment and fit a toy TabularPredictor using the change in #2865, then try to predict on the separate machine as you did before that would be very helpful.

To install the fixed version:

```
git clone -b fix_crossos_load --single-branch https://github.com/innixma/autogluon
cd autogluon && ./full_install.sh
```

Do this step on both your Windows machine and your MacOS/Linux machine to ensure you have the right code.

**Comment by Alex-Wenner-FHR** [comment]
@Innixma you bet, I will follow these steps and follow up with a reply. Thanks!

**Comment by Alex-Wenner-FHR** [comment]
To follow up on this, we tried to do Windows -> Mac per instructions. I will write this with the following disclaimer: 
`
############################## WARNING ##############################
WARNING: AutoGluon version differs from the version used to create the predictor! This may lead to instability and it is highly recommended the predictor be loaded with the exact AutoGluon version it was created with.
	Predictor Version: 0.6.3b20230215
	Current Version:   0.6.3b20230216
`

Not sure that such a minor mis match matters but I wanted it to be know. Moreover we are still seeing the following issue 



```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[10], line 1
----> 1 t.predict(data =df.head(1)[['TIME', 'V1', 'V2']])

File ~/Developer/Scripts/AG_0.7_Test/autogluon/tabular/src/autogluon/tabular/predictor/predictor.py:1378, in TabularPredictor.predict(self, data, model, as_pandas, transform_features)
   1376 self._assert_is_fit('predict')
   1377 data = self.__get_dataset(data)
-> 1378 return self._learner.predict(X=data, model=model, as_pandas=as_pandas, transform_features=transform_features)

File ~/Developer/Scripts/AG_0.7_Test/autogluon/tabular/src/autogluon/tabular/learner/abstract_learner.py:160, in AbstractTabularLearner.predict(self, X, model, as_pandas, transform_features)
    158 else:
    159     X_index = None
--> 160 y_pred_proba = self.predict_proba(X=X, model=model, as_pandas=False, as_multiclass=False, inverse_transform=False, transform_features=transform_features)
    161 problem_type = self.label_cleaner.problem_type_transform or self.problem_type
    162 y_pred = get_pred_from_proba(y_pred_proba=y_pred_proba, problem_type=problem_type)

File ~/Developer/Scripts/AG_0.7_Test/autogluon/tabular/src/autogluon/tabular/learner/abstract_learner.py:141, in AbstractTabularLearner.predict_proba(self, X, model, as_pandas, as_multiclass, inverse_transform, transform_features)
    139     if transform_features:
    140         X = self.transform_features(X)
--> 141     y_pred_proba = self.load_trainer().predict_proba(X, model=model)
    142 if inverse_transform:
    143     y_pred_proba = self.label_cleaner.inverse_transform_proba(y_pred_proba)

File ~/Developer/Scripts/AG_0.7_Test/autogluon/core/src/autogluon/core/trainer/abstract_trainer.py:575, in AbstractTrainer.predict_proba(self, X, model)
    573     model = self._get_best()
    574 cascade = isinstance(model, list)
--> 575 return self._predict_proba_model(X, model, cascade=cascade)

File ~/Developer/Scripts/AG_0.7_Test/autogluon/core/src/autogluon/core/trainer/abstract_trainer.py:2070, in AbstractTrainer._predict_proba_model(self, X, model, model_pred_proba_dict, cascade)
   2069 def _predict_proba_model(self, X, model, model_pred_proba_dict=None, cascade=False):
-> 2070     return self.get_pred_proba_from_model(model=model, X=X, model_pred_proba_dict=model_pred_proba_dict, cascade=cascade)

File ~/Developer/Scripts/AG_0.7_Test/autogluon/core/src/autogluon/core/trainer/abstract_trainer.py:589, in AbstractTrainer.get_pred_proba_from_model(self, model, X, model_pred_proba_dict, cascade)
    587 else:
    588     models = [model]
--> 589 model_pred_proba_dict = self.get_model_pred_proba_dict(X=X, models=models, model_pred_proba_dict=model_pred_proba_dict, cascade=cascade)
    590 if not isinstance(model, str):
    591     model = model.name

File ~/Developer/Scripts/AG_0.7_Test/autogluon/core/src/autogluon/core/trainer/abstract_trainer.py:815, in AbstractTrainer.get_model_pred_proba_dict(self, X, models, model_pred_proba_dict, model_pred_time_dict, record_pred_time, use_val_cache, cascade, cascade_threshold)
    811 if cascade:
    812     # Keep track of the iloc index of the current model for the rows that are predicted on.
    813     #  iloc is used because it is a very compute efficient way to track the location of rows.
    814     iloc_model_dict[model_name] = unconfident_idx
--> 815 model = self.load_model(model_name=model_name)
    816 if isinstance(model, StackerEnsembleModel):
    817     if cascade:
    818         # Need to predict only on the unconfident rows that remain.
    819         #  This requires getting the correct indices from the dependent models' prior predictions.
    820         #  Because the length of predictions in prior models differs due to early exiting,
    821         #  this logic fetches the correct indices via the iloc_model_dict.

File ~/Developer/Scripts/AG_0.7_Test/autogluon/core/src/autogluon/core/trainer/abstract_trainer.py:1360, in AbstractTrainer.load_model(self, model_name, path, model_type)
   1358 if model_type is None:
   1359     model_type = self.get_model_attribute(model=model_name, attribute='type')
-> 1360 return model_type.load(path=path, reset_paths=self.reset_paths)

File ~/Developer/Scripts/AG_0.7_Test/autogluon/core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py:887, in BaggedEnsembleModel.load(cls, path, reset_paths, low_memory, load_oof, verbose)
    885 @classmethod
    886 def load(cls, path: str, reset_paths=True, low_memory=True, load_oof=False, verbose=True):
--> 887     model = super().load(path=path, reset_paths=reset_paths, verbose=verbose)
    888     if not low_memory:
    889         model.persist_child_models(reset_paths=reset_paths)

File ~/Developer/Scripts/AG_0.7_Test/autogluon/core/src/autogluon/core/models/abstract/abstract_model.py:928, in AbstractModel.load(cls, path, reset_paths, verbose)
    926 model = load_pkl.load(path=file_path, verbose=verbose)
    927 if reset_paths:
--> 928     model.set_contexts(path)
    929 if hasattr(model, '_compiler'):
    930     if model._compiler is not None and not model._compiler.save_in_pkl:

File ~/Developer/Scripts/AG_0.7_Test/autogluon/core/src/autogluon/core/models/ensemble/stacker_ensemble_model.py:162, in StackerEnsembleModel.set_contexts(self, path_context)
    160 for model, model_path in self.base_model_paths_dict.items():
    161     model_path = os.path.abspath(model_path) + os.path.sep
--> 162     model_local_path = model_path.split(abs_path_root_orig, 1)[1]
    163     self.base_model_paths_dict[model] = self.path_root + model_local_path

IndexError: list index out of range
````

**Comment by Innixma** [comment]
@Alex-Wenner-FHR Thanks for giving it a try! I suspect there is something going on that requires a bit more than I added when absolute paths are involved. I plan to take a look as a fast-follow item to the v0.7 release and get a Windows machine to test directly with.

**Comment by Alex-Wenner-FHR** [comment]
@Innixma you bet. Thanks for looking into this, let me know if I can help any further!

**Comment by eseswaiga** [comment]
Hi, I am also facing this issue when training the model on Windows and trying to load in Linux (more specifically, on a locally-hosted Docker container). Happy to also test the solution if available.

**Comment by imrooki** [comment]
> 

How to solve it?

**Comment by doraemonlei** [comment]
Hi, I am also facing this issue when training the model on Linux(Ubuntu18.04) and trying to load on Windows(10)

**Comment by caseytomlin** [comment]
I am also seeing this `IndexError` on a single linux machine after training a new `TimeSeriesPredictor` with the same `path` as a previously trained one.

> > You are doing some pretty advanced things here without providing the original data / code, so it is hard to assist. Please provide a reproducible example on Colab so we can help.
> 
> I also met this problem, I think it may cause this: in core\trainer\abstract_trainer.py line 223:
> 
> ```
>     def create_contexts(self, path_context: str) -> (str, dict):
>         path = path_context
>         model_paths = self.get_models_attribute_dict(attribute='path')
>         for model, prev_path in model_paths.items():
>             prev_path = os.path.abspath(prev_path) + os.path.sep
>             abs_path = os.path.abspath(self.path) + os.path.sep
>             model_local_path = prev_path.split(abs_path, 1)[1]
>             new_path = path + model_local_path
>             model_paths[model] = new_path
> ```
> 
> self.path is a relative path, in my case it is `AutogluonModels/ag-20221128_161031/models/` And in some case working directory is not the code directory, so abspath will return a wrong path So, prev_path.split(abs_path, 1)[1] will get into error

Inspecting the `model_paths` dict after the second predictor is fit, I find a mix of relative and absolute paths, hence the error.

**Comment by Innixma** [comment]
Update: Please try the following PR to see if it fixes the issue: #2865 

It has been recently updated and we have tested it manually to work, but would like it confirmed by others.

**Comment by yinweisu** [comment]
Should be fixed now with https://github.com/autogluon/autogluon/pull/2865.
