### ISSUE TITLE
Why do I get errors when I try to follow "MNIST Training in PyTorch"?

### ISSUE THREAD

**Issue by yllgl** [awslabs/autogluon#251]
I copied the official document sample code to jupyter notebook,  everything was working fine before I run the code:
`myscheduler.run()`
`myscheduler.join_jobs()`
I get the errors as follows:
Process Process-3:
Traceback (most recent call last):
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/yllgl/anaconda3/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yllgl/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/yllgl/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/autogluon/scheduler/scheduler.py", line 125, in _worker
    ret = fn(**kwargs)
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/autogluon/core/decorator.py", line 58, in __call__
    output = self.f(args, **kwargs)
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/autogluon/core/decorator.py", line 138, in wrapper_call
    return func(*args, **kwargs)
  File "<ipython-input-5-06d9a13f5865>", line 8, in ag_train_mnist
    return train_mnist(args, reporter)
  File "<ipython-input-3-18edfcf0c2bd>", line 56, in train_mnist
    test(epoch)
  File "<ipython-input-3-18edfcf0c2bd>", line 41, in test
    for batch_idx, (inputs, targets) in enumerate(testloader):
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 771, in _get_data
    success, data = self._try_get_data()
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 737, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 6816, 6827) exited unexpectedly
Process Process-4:
Traceback (most recent call last):
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/yllgl/anaconda3/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yllgl/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/yllgl/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/autogluon/scheduler/scheduler.py", line 125, in _worker
    ret = fn(**kwargs)
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/autogluon/core/decorator.py", line 58, in __call__
    output = self.f(args, **kwargs)
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/autogluon/core/decorator.py", line 138, in wrapper_call
    return func(*args, **kwargs)
  File "<ipython-input-5-06d9a13f5865>", line 8, in ag_train_mnist
    return train_mnist(args, reporter)
  File "<ipython-input-3-18edfcf0c2bd>", line 56, in train_mnist
    test(epoch)
  File "<ipython-input-3-18edfcf0c2bd>", line 41, in test
    for batch_idx, (inputs, targets) in enumerate(testloader):
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 771, in _get_data
    success, data = self._try_get_data()
  File "/home/yllgl/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 737, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 6846, 6858) exited unexpectedly

here is my jupyter notebook file（I renamed the suffix .ipynb to .txt in order to upload files.）:
[Untitled.txt](https://github.com/awslabs/autogluon/files/4132376/Untitled.txt)

OS：  Ubuntu 16.04.6 LTS
python version：3.7

**Comment by yllgl** [comment]
I comment out the code :
"trainloader = torch.utils.data.DataLoader(trainset, batch_size=128, shuffle=True, num_workers=2)" and change it to 
"trainloader = torch.utils.data.DataLoader(trainset, batch_size=128, shuffle=True)"
it works well.

**Comment by Innixma** [comment]
@zhanghang1989 This looks like a bug that still requires a manual fix by the user, can you confirm if this is still the case?
