### ISSUE TITLE
Could not pickle object as excessively deep recursion required

### ISSUE THREAD

**Issue by dmxj** [awslabs/autogluon#276]
**when I try object detection task, use tiny motorbike dataset privided by demo, but some error happen**

> Traceback (most recent call last):
  File "train.py", line 15, in <module>
    time_limits=time_limits)
  File "/opt/conda/lib/python3.6/site-packages/autogluon/task/object_detection/object_detection.py", line 257, in fit
    scheduler_options)
  File "/opt/conda/lib/python3.6/site-packages/autogluon/task/base/base_task.py", line 43, in run_fit
    scheduler.run()
  File "/opt/conda/lib/python3.6/site-packages/autogluon/scheduler/fifo.py", line 146, in run
    self.schedule_next()
  File "/opt/conda/lib/python3.6/site-packages/autogluon/scheduler/fifo.py", line 177, in schedule_next
    self.add_job(task, **extra_kwargs)
  File "/opt/conda/lib/python3.6/site-packages/autogluon/scheduler/fifo.py", line 223, in add_job
    job = cls._start_distributed_job(task, cls.RESOURCE_MANAGER, self.env_sem)
  File "/opt/conda/lib/python3.6/site-packages/autogluon/scheduler/scheduler.py", line 102, in _start_distributed_job
    env_sem)
  File "/opt/conda/lib/python3.6/site-packages/distributed/client.py", line 1485, in submit
    actors=actor,
  File "/opt/conda/lib/python3.6/site-packages/distributed/client.py", line 2461, in _graph_to_futures
    "tasks": valmap(dumps_task, dsk3),
  File "cytoolz/dicttoolz.pyx", line 165, in cytoolz.dicttoolz.valmap
  File "cytoolz/dicttoolz.pyx", line 190, in cytoolz.dicttoolz.valmap
  File "/opt/conda/lib/python3.6/site-packages/distributed/worker.py", line 3211, in dumps_task
    return {"function": dumps_function(task[0]), "args": warn_dumps(task[1:])}
  File "/opt/conda/lib/python3.6/site-packages/distributed/worker.py", line 3220, in warn_dumps
    b = dumps(obj)
  File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 51, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/opt/conda/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 706, in dumps
    cp.dump(obj)
  File "/opt/conda/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 150, in dump
    raise pickle.PicklingError(msg)
_pickle.PicklingError: Could not pickle object as excessively deep recursion required.
  0%|                                                                                                | 0/2 [00:02<?, ?it/s]

**and here is the try code**

> import autogluon as ag
from autogluon import ObjectDetection as task
import os
data_root = "/root/workspace/try_auto_gluon/dataset/tiny_motorbike/tiny_motorbike"
dataset_train = task.Dataset(data_root, classes=('motorbike',))
time_limits = 5*60*60  # 5 hours
epochs = 30
detector = task.fit(dataset_train,
                    num_trials=2,
                    epochs=epochs,
                    lr=ag.Categorical(5e-4, 1e-4),
                    ngpus_per_trial=1,
                    time_limits=time_limits)
dataset_test = task.Dataset(data_root, index_file_name='test', classes=('motorbike',))
test_map = detector.evaluate(dataset_test)
print("mAP on test dataset: {}".format(test_map[1][1]))

**Comment by zhanghang1989** [comment]
Could you check the `dask` and `distributed` package versions?
```bash
pip show dask
pip show distributed
```

**Comment by dmxj** [comment]
> Could you check the `dask` and `distributed` package versions?
> 
> ```shell
> pip show dask
> pip show distributed
> ```

@zhanghang1989 the `dash` and `distributed ` version is 2.6.0
![image](https://user-images.githubusercontent.com/6835981/74511870-ed3eb600-4f41-11ea-8815-c831a58b7a79.png)

**Comment by zhanghang1989** [comment]
The dask and distributed versions are correct. Sorry that I could not reproduce the issue on my machine. What's your environment settings?
