### ISSUE TITLE
autogluon-0.0.6 tabular_prediction predictor.evaluate fail in Python 3.6.9

### ISSUE THREAD

**Issue by elife33** [awslabs/autogluon#371]
Traceback (most recent call last):
  File "t2.py", line 12, in <module>
    performance = predictor.evaluate(test_data)
  File "/home/elife/.local/lib/python3.6/site-packages/autogluon/task/tabular_prediction/predictor.py", line 148, in evaluate
    perf = self._learner.score(dataset)
  File "/home/elife/.local/lib/python3.6/site-packages/autogluon/utils/tabular/ml/learner/abstract_learner.py", line 205, in score
    return trainer.score(X=X, y=y, model=model)
  File "/home/elife/.local/lib/python3.6/site-packages/autogluon/utils/tabular/ml/trainer/abstract_trainer.py", line 668, in score
    y_pred_ensemble = self.predict(X=X, model=model)
  File "/home/elife/.local/lib/python3.6/site-packages/autogluon/utils/tabular/ml/trainer/abstract_trainer.py", line 609, in predict
    return self.predict_model(X, self.model_best)
  File "/home/elife/.local/lib/python3.6/site-packages/autogluon/utils/tabular/ml/trainer/abstract_trainer.py", line 627, in predict_model
    model = self.load_model(model)
  File "/home/elife/.local/lib/python3.6/site-packages/autogluon/utils/tabular/ml/trainer/abstract_trainer.py", line 816, in load_model
    return model_type.load(path=path, reset_paths=self.reset_paths)
  File "/home/elife/.local/lib/python3.6/site-packages/autogluon/utils/tabular/ml/models/ensemble/bagged_ensemble_model.py", line 358, in load
    obj.set_contexts(path)
  File "/home/elife/.local/lib/python3.6/site-packages/autogluon/utils/tabular/ml/models/ensemble/stacker_ensemble_model.py", line 124, in set_contexts
    path_root_orig = self.path_root
AttributeError: 'WeightedEnsembleModel' object has no attribute 'path_root'

Tested in ubuntu and Mac OS X(python in Mac OS X is 3.7.7)
autogluon-0.0.5 works fine

**Comment by elife33** [comment]
python in Mac OS X is 3.7.7

**Comment by elife33** [comment]
autogluon-0.0.6 not support model of autogluon-0.0.5

**Comment by Innixma** [comment]
Thanks for clarifying! It may be useful in future for us to add a message warning someone who loads a model trained on a different version of AutoGluon. At the current time of development, it will very likely be the case that models trained in old versions will not work on newer versions.
