### ISSUE TITLE
ImportError: cannot import name 'MaskedArray'

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#461]
Full traceback:

```
>>> import autogluon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/virtual/test007/lib/python3.6/site-packages/autogluon/__init__.py", line 10, in <module>
    from . import scheduler, searcher, utils
  File "/home/ubuntu/virtual/test007/lib/python3.6/site-packages/autogluon/scheduler/__init__.py", line 6, in <module>
    from .fifo import *
  File "/home/ubuntu/virtual/test007/lib/python3.6/site-packages/autogluon/scheduler/fifo.py", line 19, in <module>
    from ..searcher import BaseSearcher
  File "/home/ubuntu/virtual/test007/lib/python3.6/site-packages/autogluon/searcher/__init__.py", line 2, in <module>
    from .skopt_searcher import *
  File "/home/ubuntu/virtual/test007/lib/python3.6/site-packages/autogluon/searcher/skopt_searcher.py", line 6, in <module>
    from skopt import Optimizer
  File "/home/ubuntu/virtual/test007/lib/python3.6/site-packages/skopt/__init__.py", line 54, in <module>
    from .searchcv import BayesSearchCV
  File "/home/ubuntu/virtual/test007/lib/python3.6/site-packages/skopt/searchcv.py", line 16, in <module>
    from sklearn.utils.fixes import MaskedArray
ImportError: cannot import name 'MaskedArray'
>>> 
```

This is caused because sklearn updated to 0.23, and skopt breaks with sklearn==0.23. To fix manually, downgrade sklearn to 0.22.

AutoGluon Fix PR: #460 

Skopt Issue: https://github.com/scikit-optimize/scikit-optimize/issues/902

**Comment by Innixma** [comment]
Resolved in 0.0.9
