### ISSUE TITLE
Failed to clean up lingering worker directories in path : %s

### ISSUE THREAD

**Issue by nitinmnsn** [awslabs/autogluon#476]
Post trying autogluon for the first time here are a few things i have noticed:
1. Cannot delete producer.log. `rm producer.log` works without an error status but the producer.log is still there. Pre and post inode numbers for producer.log are different so i am guessing some processes are created outside the scope of jupyter notebook that persist even after i kill the jupyter kernel and recreate the file. 
2. Same as 1 but for consumer.log
3. same as 1 and 2 but for dask-worker-space/*.dirlock
4. Each time i run autogluon on a task i get
```
distributed.diskutils - ERROR - Failed to clean up lingering worker directories in path: %s 
Traceback (most recent call last):
  File "/home/nitin/anaconda3/envs/automlgluon/lib/python3.6/site-packages/distributed/diskutils.py", line 237, in new_work_dir
    self._purge_leftovers()
  File "/home/nitin/anaconda3/envs/automlgluon/lib/python3.6/site-packages/distributed/diskutils.py", line 168, in _purge_leftovers
    if self._check_lock_or_purge(path):
  File "/home/nitin/anaconda3/envs/automlgluon/lib/python3.6/site-packages/distributed/diskutils.py", line 203, in _check_lock_or_purge
    lock.acquire()
  File "/home/nitin/anaconda3/envs/automlgluon/lib/python3.6/site-packages/distributed/locket.py", line 196, in acquire
    self._lock.acquire(self._timeout, self._retry_period)
  File "/home/nitin/anaconda3/envs/automlgluon/lib/python3.6/site-packages/distributed/locket.py", line 125, in acquire
    lock.acquire(timeout, retry_period)
  File "/home/nitin/anaconda3/envs/automlgluon/lib/python3.6/site-packages/distributed/locket.py", line 167, in acquire
    self._file = open(self._path, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '/monsoondrive/central/Experiments/dask-worker-space/worker-tmnn2i84.dirlock'
```

Is it somethig related to file system that i am on. I am working on an mounted disk on an azure VM

**Comment by Innixma** [comment]
Interesting, I have not seen this error before. It may be due to the way your mounted disk is implemented. I have not tested on azure. On EC2 with EBS it works without issue for me.

Regarding the extra `dask-worker-space` files, this is a bug that exists somewhere in AutoGluon NLP (I believe), which on `import autogluon` creates dask workers needlessly. To my knowledge they do not persist after killing AutoGluon, but I may be mistaken in your case. If you can find examples of these processes running after AutoGluon terminates, that would be very good information for us to troubleshoot. Furthermore, I've never had difficulty removing the dask worker directory after an AutoGluon run before, so this is also odd. Perhaps it is something caused by azure? Could you try to reproduce locally? Also ensure your OS is ubuntu, we haven't tested other Linux distributions heavily.

Regarding `consumer.log` and `producer.log`, I have never personally seen these files before, so perhaps they aren't from autogluon?

Best,
Nick
