### ISSUE TITLE
How to save the model created with an ENAS_Scheduler?

### ISSUE THREAD

**Issue by andyDoucette** [awslabs/autogluon#558]
We have this nice tutorial showing how to use the ENAS_Scheduler to train a model.

[ENAS Tutorial](https://autogluon.mxnet.io/tutorials/nas/enas_proxylessnas.html) 

My question is:  How do we save and load trained models created that way?  I've tried 5 different ways and none of them seem to work.  

Based on what I read, the one I think I'm supposed to use is this:

`
mynet.export(modelFile, epoch=numEpochsTrained)
`

However, that produces this error message when I run it:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/usr/lib/python3.6/bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/app/src/cli/boundryDetector.py", line 2, in <module>
    import sys,os;
  File "/app/src/code/boundryDetector/../lib/click/src/click/core.py", line 857, in __call__
    return self.main(*args, **kwargs)
  File "/app/src/code/boundryDetector/../lib/click/src/click/core.py", line 810, in main
    rv = self.invoke(ctx)
  File "/app/src/code/boundryDetector/../lib/click/src/click/core.py", line 1099, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/src/code/boundryDetector/../lib/click/src/click/core.py", line 613, in invoke
    return callback(*args, **kwargs)
  File "/app/src/cli/boundryDetector.py", line 108, in boundry_detector
    dnn.save(modelFile)
  File "/app/src/code/boundryDetector/./dnn/save.py", line 12, in save
    s.model.export(modelFile, epoch=s.numEpochsTrained)
  File "/usr/local/lib/python3.6/dist-packages/mxnet/gluon/block.py", line 1106, in export
    assert name in aux_names
AssertionError
```

I'm using:
```
autogluon==0.0.11
mxnet==1.6.0
```

Your kind assistance would be greatly appreciated. :)

**Comment by Innixma** [comment]
@zhreshold Could you take a look at this?

**Comment by zhreshold** [comment]
@andyDoucette Hi, the fix to export is available here: https://github.com/awslabs/autogluon/pull/559

The remaining issue is that you can only use the exported model for inference, but may not be able to load it back as the current implementation of ENAS is based on a highly dynamically wrapped structure that can't be pickled or saved.
The good news is that the exported model can be imported into mxnet without extra dependency.

**Comment by andyDoucette** [comment]
@zhreshold Thank you very much! :)  Once this all gets put into master, I'll try it out on my side and report back.
