### ISSUE TITLE
How to load a pre trained object detection .params file in auto gluon for inferencing ?

### ISSUE THREAD

**Issue by Pentar0o** [awslabs/autogluon#599]
Hi,

I've trained an object detection network with autogluon and I've saved the parameters with :
network = detector.model
network.save_parameters('network.params')

When I try in another python script to load it for inferencing with : 
detection = autogluon.task.object_detection.detector.load('YeroAutoGluon_090.params')

I have this error : 

Traceback (most recent call last):
  File "TestImageYoloYero.py", line 37, in <module>
    main(sys.argv[1])
  File "TestImageYoloYero.py", line 30, in main
    Yeronator(fichier)
  File "TestImageYoloYero.py", line 18, in Yeronator
    detection = autogluon.task.object_detection.detector.load('YeroAutoGluon_090.params')
  File "/home/penta/.local/lib/python3.8/site-packages/autogluon/utils/serialization.py", line 79, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/penta/.local/lib/python3.8/site-packages/autogluon/utils/serialization.py", line 361, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x12'.

Thank you for your help.

**Comment by zhreshold** [comment]
This issue is fixed in autogluon v0.1 therefore I am closing this, feel free to reach out if you still need the legacy models to be loaded
