### ISSUE TITLE
distributed.core - ERROR - 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by ChengTsang** [awslabs/autogluon#832]
Hi, when i clone the new version code and train it on my own data, I met a issue: 

distributed.core - ERROR - 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/distributed/core.py", line 589, in handle_stream
    handler(**merge(extra, msg))
  File "/usr/local/lib/python3.7/dist-packages/distributed/scheduler.py", line 2286, in update_graph_hlg
    dsk, dependencies, annotations = highlevelgraph_unpack(hlg)
  File "/usr/local/lib/python3.7/dist-packages/distributed/protocol/highlevelgraph.py", line 126, in highlevelgraph_unpack
    dumped_hlg, object_hook=msgpack_decode_default, use_list=False, **msgpack_opts
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
distributed.core - ERROR - Exception while handling op register-client
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/distributed/core.py", line 517, in handle_comm
    result = await result
  File "/usr/local/lib/python3.7/dist-packages/distributed/scheduler.py", line 3149, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/usr/local/lib/python3.7/dist-packages/distributed/core.py", line 589, in handle_stream
    handler(**merge(extra, msg))
  File "/usr/local/lib/python3.7/dist-packages/distributed/scheduler.py", line 2286, in update_graph_hlg
    dsk, dependencies, annotations = highlevelgraph_unpack(hlg)
  File "/usr/local/lib/python3.7/dist-packages/distributed/protocol/highlevelgraph.py", line 126, in highlevelgraph_unpack
    dumped_hlg, object_hook=msgpack_decode_default, use_list=False, **msgpack_opts
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f9538d03c18>>, <Task finished coro=<Server.handle_comm() done, defined at /usr/local/lib/python3.7/dist-packages/distributed/core.py:425> exception=UnicodeDecodeError('utf-8', b'\x80\x04\x950\x00\x00\x00\x00\x00\x00\x00\x8c\x1aautogluon.core.utils.utils\x94\x8c\rget_cpu_count\x94\x93\x94.', 0, 1, 'invalid start byte')>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.7/dist-packages/distributed/core.py", line 517, in handle_comm
    result = await result
  File "/usr/local/lib/python3.7/dist-packages/distributed/scheduler.py", line 3149, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/usr/local/lib/python3.7/dist-packages/distributed/core.py", line 589, in handle_stream
    handler(**merge(extra, msg))
  File "/usr/local/lib/python3.7/dist-packages/distributed/scheduler.py", line 2286, in update_graph_hlg
    dsk, dependencies, annotations = highlevelgraph_unpack(hlg)
  File "/usr/local/lib/python3.7/dist-packages/distributed/protocol/highlevelgraph.py", line 126, in highlevelgraph_unpack
    dumped_hlg, object_hook=msgpack_decode_default, use_list=False, **msgpack_opts
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Warning: Exception caused LightGBM to fail during hyperparameter tuning... Skipping this model.
Traceback (most recent call last):
  File "/opt/tiger/hadron2/autogluon/tabular/src/autogluon/tabular/trainer/abstract_trainer.py", line 996, in _train_single_full
    hpo_models, hpo_model_performances, hpo_results = model.hyperparameter_tune(X_train=X_train, y_train=y_train, X_val=X_val, y_val=y_val, scheduler_options=(self._scheduler_func, self._scheduler_options), verbosity=self.verbosity)
  File "/opt/tiger/hadron2/autogluon/tabular/src/autogluon/tabular/models/lgb/lgb_model.py", line 336, in hyperparameter_tune
    scheduler = scheduler_func(lgb_trial, **scheduler_options)
  File "/opt/tiger/hadron2/autogluon/core/src/autogluon/core/scheduler/fifo.py", line 140, in __init__
    super().__init__(kwargs.get('dist_ip_addrs'))
  File "/opt/tiger/hadron2/autogluon/core/src/autogluon/core/scheduler/scheduler.py", line 73, in __init__
    cls.resource_manager.add_remote(cls.remote_manager.get_remotes())
  File "/opt/tiger/hadron2/autogluon/core/src/autogluon/core/scheduler/resource/dist_manager.py", line 29, in add_remote
    cls.NODE_RESOURCE_MANAGER[remote] = NodeResourceManager(remote)
  File "/opt/tiger/hadron2/autogluon/core/src/autogluon/core/scheduler/resource/dist_manager.py", line 148, in __init__
    self.MAX_CPU_COUNT = get_remote_cpu_count(remote)
  File "/opt/tiger/hadron2/autogluon/core/src/autogluon/core/scheduler/resource/resource.py", line 96, in get_remote_cpu_count
    return ret.result()
  File "/usr/local/lib/python3.7/dist-packages/distributed/client.py", line 226, in result
    raise result
concurrent.futures._base.CancelledError: get_cpu_count-dee517fe40a7ea4e356710b0c13d3a03
get_cpu_count-dee517fe40a7ea4e356710b0c13d3a03
No base models to train on, skipping weighted ensemble...
Traceback (most recent call last):
  File "rh2_test.py", line 46, in <module>
    search_metric='accuracy')
  File "/opt/tiger/hadron2/autohadron/autohadron/pipelines/train_pipeline.py", line 64, in train
    nthreads_per_trial=30)
  File "/opt/tiger/hadron2/autogluon/tabular/src/autogluon/tabular/task/tabular_prediction/presets_configs.py", line 10, in _call
    return f(*gargs, **gkwargs)
  File "/opt/tiger/hadron2/autogluon/tabular/src/autogluon/tabular/task/tabular_prediction/tabular_prediction.py", line 700, in fit
    time_limit=time_limits_orig, save_data=cache_data, save_bagged_folds=save_bagged_folds, verbosity=verbosity)
  File "/opt/tiger/hadron2/autogluon/tabular/src/autogluon/tabular/learner/abstract_learner.py", line 85, in fit
    return self._fit(X=X, X_val=X_val, **kwargs)
  File "/opt/tiger/hadron2/autogluon/tabular/src/autogluon/tabular/learner/default_learner.py", line 96, in _fit
    trainer.train(X, y, X_val, y_val, X_unlabeled=X_unlabeled, holdout_frac=holdout_frac, time_limit=time_limit_trainer, **trainer_fit_kwargs)
  File "/opt/tiger/hadron2/autogluon/tabular/src/autogluon/tabular/trainer/auto_trainer.py", line 48, in train
    stack_ensemble_levels=stack_ensemble_levels, time_limit=time_limit, core_kwargs=core_kwargs)
  File "/opt/tiger/hadron2/autogluon/tabular/src/autogluon/tabular/trainer/abstract_trainer.py", line 1190, in _train_multi_and_ensemble
    raise ValueError('AutoGluon did not successfully train any models')
ValueError: AutoGluon did not successfully train any models

**Comment by Innixma** [comment]
Hi, thanks for making an issue! Could you provide a minimally reproducible example (say with 10 rows of training data provided that cause the issue?). This would help immensely in debugging.

**Comment by ChengTsang** [comment]
> Hi, thanks for making an issue! Could you provide a minimally reproducible example (say with 10 rows of training data provided that cause the issue?). This would help immensely in debugging.

Thanks for your reply, you can reproduce this issue with whatever data set such as https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv

**Comment by ChengTsang** [comment]
> > Hi, thanks for making an issue! Could you provide a minimally reproducible example (say with 10 rows of training data provided that cause the issue?). This would help immensely in debugging.
> 
> Thanks for your reply, you can reproduce this issue with whatever data set such as https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv

I just clone the new code and install with full_install.sh not with pip.

**Comment by gradientsky** [comment]
What system codepage are you running this code on?

**Comment by gradientsky** [comment]
Another sanity check: I see a distributed scheduler was used. Did all the machines had same version of dask?

**Comment by ChengTsang** [comment]
halo, I fixed the problem by use another version of distributed.

**Comment by ChengTsang** [comment]
halo, I fixed the problem by using another version of distributed.

**Comment by bhavi289** [comment]
@ChengTsang 

Which version of "distributed" did you use?
