### ISSUE TITLE
AutoGluon Text crashes on p4d instance

### ISSUE THREAD

**Issue by sflender** [awslabs/autogluon#880]
AutoGluon Text crashes on a p4d instance. 

**install history:**
```
conda create --name py37AGN python=3.7
conda activate py37AGN
pip install --upgrade "mxnet_cu101<2.0.0"
git clone https://github.com/awslabs/autogluon.git
cd autogluon/
bash full_install.sh 
```

**Error log:**

```
2021-01-22 00:27:46,874 - root - INFO - Process training set...
2021-01-22 00:27:47,926 - root - INFO - Done!
2021-01-22 00:27:47,926 - root - INFO - Process dev set...
2021-01-22 00:27:48,167 - root - INFO - Done!
/home/ec2-user/anaconda3/envs/py37AGN/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
 len(cache))
Traceback (most recent call last):
 File "dgtext.py", line 120, in <module>
  main()
 File "dgtext.py", line 95, in main
  verbosity=3
 File "/home/ec2-user/anaconda3/envs/py37AGN/lib/python3.7/site-packages/mxnet/util.py", line 297, in _with_np_shape
  return func(*args, **kwargs)
 File "/home/ec2-user/anaconda3/envs/py37AGN/lib/python3.7/site-packages/mxnet/util.py", line 481, in _with_np_array
  return func(*args, **kwargs)
 File "/home/ec2-user/autogluon/text/src/autogluon/text/text_prediction/text_prediction.py", line 533, in fit
  ignore_warning=verbosity <= 2)
 File "/home/ec2-user/anaconda3/envs/py37AGN/lib/python3.7/site-packages/mxnet/util.py", line 297, in _with_np_shape
  return func(*args, **kwargs)
 File "/home/ec2-user/anaconda3/envs/py37AGN/lib/python3.7/site-packages/mxnet/util.py", line 481, in _with_np_array
  return func(*args, **kwargs)
 File "/home/ec2-user/autogluon/text/src/autogluon/text/text_prediction/models/basic_v1.py", line 653, in train
  raise RuntimeError('No training job has been completed! '
RuntimeError: No training job has been completed! There are two possibilities: 1) The time_limits is too small, or 2) There are some internal errors in AutoGluon. For the first case, you can increase the time_limits or set it to None, e.g., setting "TextPrediction.fit(..., time_limits=None). To further investigate the root cause, you can also try to train with "verbosity=3", i.e., TextPrediction.fit(..., verbosity=3).
```

**pip freeze:**

```
attrs==20.3.0
autocfg==0.0.6
-e git+https://github.com/awslabs/autogluon.git@18fb70631778879b24e6e48369fa334656772c31#egg=autogluon&subdirectory=autogluon
autogluon-contrib-nlp==0.0.1b20210112
-e git+https://github.com/awslabs/autogluon.git@18fb70631778879b24e6e48369fa334656772c31#egg=autogluon.core&subdirectory=core
-e git+https://github.com/awslabs/autogluon.git@18fb70631778879b24e6e48369fa334656772c31#egg=autogluon.extra&subdirectory=extra
-e git+https://github.com/awslabs/autogluon.git@18fb70631778879b24e6e48369fa334656772c31#egg=autogluon.mxnet&subdirectory=mxnet
-e git+https://github.com/awslabs/autogluon.git@18fb70631778879b24e6e48369fa334656772c31#egg=autogluon.tabular&subdirectory=tabular
-e git+https://github.com/awslabs/autogluon.git@18fb70631778879b24e6e48369fa334656772c31#egg=autogluon.text&subdirectory=text
-e git+https://github.com/awslabs/autogluon.git@18fb70631778879b24e6e48369fa334656772c31#egg=autogluon.vision&subdirectory=vision
autograd==1.3
bcrypt==3.2.0
beautifulsoup4==4.9.3
blis==0.7.4
bokeh==2.1.1
boto3==1.16.58
botocore==1.19.58
Bottleneck==1.3.2
catalogue==1.0.0
catboost==0.24.4
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
click==7.1.2
cloudpickle==1.6.0
ConfigSpace==0.4.16
contextvars==2.4
cryptography==3.3.1
cycler==0.10.0
cymem==2.0.5
Cython==0.29.21
d8==0.0.2
dask==2021.1.0
decorator==4.4.2
decord==0.4.2
dill==0.3.3
distributed==2021.1.0
fastai==1.0.61
fastprogress==1.0.0
flake8==3.8.4
future==0.18.2
gluoncv==0.9.1.post0
graphviz==0.8.4
HeapDict==1.0.1
idna==2.10
immutables==0.14
importlib-metadata==3.4.0
iniconfig==1.1.1
Jinja2==2.11.2
jmespath==0.10.0
joblib==1.0.0
kaggle==1.5.10
kiwisolver==1.3.1
liac-arff==2.5.0
lightgbm==3.1.1
MarkupSafe==1.1.1
matplotlib==3.3.3
mccabe==0.6.1
msgpack==1.0.2
murmurhash==1.0.5
mxnet-cu101==1.7.0
networkx==2.5
numexpr==2.7.2
numpy==1.19.5
nvidia-ml-py3==7.352.0
opencv-python==4.5.1.48
openml==0.11.0
packaging==20.8
pandas==1.2.1
paramiko==2.7.2
Pillow==6.2.1
plac==1.1.3
plotly==4.14.3
pluggy==0.13.1
portalocker==2.0.0
preshed==3.0.5
protobuf==3.14.0
psutil==5.7.0
py==1.10.0
pyaml==20.4.0
pyarrow==1.0.0
pycodestyle==2.6.0
pycparser==2.20
pyflakes==2.2.0
PyNaCl==1.4.0
pyparsing==2.4.7
pytest==6.2.1
python-dateutil==2.8.1
python-slugify==4.0.1
pytz==2020.5
PyYAML==5.4.1
regex==2020.11.13
requests==2.25.1
retrying==1.3.3
s3transfer==0.3.4
sacrebleu==1.5.0
sacremoses==0.0.43
scikit-learn==0.23.2
scikit-optimize==0.8.1
scipy==1.4.1
sentencepiece==0.1.95
six==1.15.0
sortedcontainers==2.3.0
soupsieve==2.1
spacy==2.3.5
srsly==1.0.5
tblib==1.7.0
tensorboardX==2.1
text-unidecode==1.3
thinc==7.4.5
threadpoolctl==2.1.0
tokenizers==0.9.4
toml==0.10.2
toolz==0.11.1
torch==1.7.1
torchvision==0.8.2
tornado==6.1
tqdm==4.56.0
typing-extensions==3.7.4.3
urllib3==1.26.2
wasabi==0.8.0
xgboost==1.2.1
xmltodict==0.12.0
yacs==0.1.8
zict==2.0.0
zipp==3.4.0

```

**Comment by leezu** [comment]
Would you need a Cuda 11 build for P4?

**Comment by sflender** [comment]
That's possible, need to do more research. If that's true, I think a problem is that there's no pip-installable version of mxnet with cuda 11.

**Comment by leezu** [comment]
While official MXNet is pending, you can use the AWS MX s3://aws-mx-pypi/1.8.0/aws_mx_cu110-1.8.0-py2.py3-none-manylinux2014_x86_64.whl

**Comment by sflender** [comment]
Thanks, I'll give this a try

**Comment by sflender** [comment]
I tried that, and get a different error. Somehow the libcudnn.so file is missing.

Install history:

```
conda create --name py37AGNcu11 python=3.7
conda activate py37AGNcu11
aws s3 cp s3://aws-mx-pypi/1.8.0/aws_mx_cu110-1.8.0-py2.py3-none-manylinux2014_x86_64.whl .
pip install aws_mx_cu110-1.8.0-py2.py3-none-manylinux2014_x86_64.whl 
cd autogluon/
bash full_install.sh 
```

Error:


```
  File "/home/ec2-user/anaconda3/envs/py37AGNcu11/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudnn.so.8: cannot open shared object file: No such file or directory
```

**Comment by leezu** [comment]
Your OS is too old. You need CuDNN 8

**Comment by Innixma** [comment]
I believe we have successfully used p4 instances recently with AutoGluon Text. If you are still having issues, please re-open this ticket and I can ping the users who were using p4 instances to provide instructions.
