### ISSUE TITLE
AG Text non-deterministic crashes, possibly due to Dask backend

### ISSUE THREAD

**Issue by sflender** [awslabs/autogluon#886]
Sometimes AG Text crashes with the error message below. We suspect that this could be because of issues with the Dask backend in HPO. 

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/py37AGN/lib/python3.7/site-packages/distributed/comm/core.py", line 288, in connect
    timeout=min(intermediate_cap, time_left()),
  File "/home/ubuntu/anaconda3/envs/py37AGN/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/py37AGN/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/autogluon/core/src/autogluon/core/scheduler/reporter.py", line 202, in run
    self.dist_reporter(**reported_result)
  File "/home/ubuntu/autogluon/core/src/autogluon/core/scheduler/reporter.py", line 63, in __call__
    self._queue.put(kwargs.copy())
  File "/home/ubuntu/anaconda3/envs/py37AGN/lib/python3.7/site-packages/distributed/queues.py", line 224, in put
    return self.client.sync(self._put, value, timeout=timeout, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py37AGN/lib/python3.7/site-packages/distributed/client.py", line 840, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/ubuntu/anaconda3/envs/py37AGN/lib/python3.7/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/home/ubuntu/anaconda3/envs/py37AGN/lib/python3.7/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/home/ubuntu/anaconda3/envs/py37AGN/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/ubuntu/anaconda3/envs/py37AGN/lib/python3.7/site-packages/distributed/queues.py", line 210, in _put
    data=value, timeout=timeout, name=self.name
  File "/home/ubuntu/anaconda3/envs/py37AGN/lib/python3.7/site-packages/distributed/core.py", line 855, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/home/ubuntu/anaconda3/envs/py37AGN/lib/python3.7/site-packages/distributed/core.py", line 1010, in connect
    **self.connection_args,
  File "/home/ubuntu/anaconda3/envs/py37AGN/lib/python3.7/site-packages/distributed/comm/core.py", line 310, in connect
    ) from active_exception
OSError: Timed out trying to connect to inproc://172.31.33.38/3297/1 after 10 s
```

**Comment by sflender** [comment]
The issue happens both in python 3.6 and 3.7.

**Comment by Innixma** [comment]
This should be fixed now with Text overhaul and local sequential scheduler HPO management overhaul in pre-release. Please re-open if issue persists.
