### ISSUE TITLE
Support Inference on AWS Lambda

### ISSUE THREAD

**Issue by tiru1930** [awslabs/autogluon#921]
I was trying to run the aws inference inside aws lambda function  and i got this error 

```
[ERROR] OSError: [Errno 38] Function not implemented
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/app_lambda.py", line 4, in <module>
    from autogluon import TabularPrediction as Task
  File "/usr/local/lib/python3.7/site-packages/autogluon/__init__.py", line 20, in <module>
    from . import scheduler, searcher, utils
  File "/usr/local/lib/python3.7/site-packages/autogluon/scheduler/__init__.py", line 1, in <module>
    from .import remote, resource
  File "/usr/local/lib/python3.7/site-packages/autogluon/scheduler/remote/__init__.py", line 2, in <module>
    from .remote import *
  File "/usr/local/lib/python3.7/site-packages/autogluon/scheduler/remote/remote.py", line 60, in <module>
    class Remote(Client):
  File "/usr/local/lib/python3.7/site-packages/autogluon/scheduler/remote/remote.py", line 61, in Remote
    LOCK = mp.Lock()
  File "/usr/local/lib/python3.7/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/local/lib/python3.7/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/local/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
```
looks like there an issue with aws multi-processing

**Comment by Innixma** [comment]
AutoGluon does not currently support AWS Lambda for a variety of reasons. Most importantly, multiprocessing methods that AutoGluon makes heavy use of are not enabled in Lambda. Either Lambda must enable these multiprocessing options, or AutoGluon must have a configuration which does not make use of them to work on Lambda.

AutoGluon does work on EC2 and Fargate without issue, so I would recommend using those options for now.

If anyone wants to deep dive into what is necessary to enable AutoGluon on Lambda, then please post your findings here and we can consider implementing the required solution, however I expect it will have to be quite complex, given that individual models might also make use of multiprocessing.

**Comment by paulacampigotto** [comment]
@Innixma are these multiprocessing methods used in tabular prediction? 
In case it's not, I think it could be implemented a separate module for the tabular prediction (for example).
Then we would be able to use it in aws lambdas, just to load a model and make inferences.

**Comment by gradientsky** [comment]
This is possible now. Please refer to the [tutorial](https://auto.gluon.ai/stable/tutorials/cloud_fit_deploy/cloud-aws-lambda-deployment.html) for more details.
