### ISSUE TITLE
How to use .rec for ENAS?

### ISSUE THREAD

**Issue by jeonginseo** [awslabs/autogluon#931]
First of all, thank you for your awesome work.

**I tried to import my custom image dataset (made by im2rec.py) for ENAS example as below:**
(source : http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-388/3/tutorials/nas/enas_mnist.html#reference) 

**train_set = mx.gluon.data.RecordFileDataset('train.rec')**

**but it failed with these errors:**
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "ag_enas.py", line 62, in <module>
    plot_frequency=10, update_arch_frequency=5)
  File "/home/jay/.local/lib/python3.6/site-packages/autogluon/contrib/enas/enas_scheduler.py", line 48, in __init__
    train_args, val_args)
  File "/home/jay/.local/lib/python3.6/site-packages/autogluon/contrib/enas/enas_scheduler.py", line 95, in initialize_miscs
    num_workers=num_cpus, prefetch=0, sample_times=self.controller_batch_size)
  File "/home/jay/.local/lib/python3.6/site-packages/autogluon/utils/dataloader.py", line 217, in __init__
    **sampler = _sampler.RandomSampler(len(dataset))
TypeError: object of type 'NoneType' has no len()**
Exception ignored in: <bound method DataLoader.__del__ of <autogluon.utils.dataloader.DataLoader object at 0x7f95a8a44128>>
Traceback (most recent call last):
  File "/home/jay/.local/lib/python3.6/site-packages/autogluon/utils/dataloader.py", line 278, in __del__
    **if self._worker_pool:**
**AttributeError: 'DataLoader' object has no attribute '_worker_pool'**

What can I do for this?
I'm using mxnet-cu101==1.7.0 and installed autogluon using pip (0.0.15).

Thanks in advance.

**Comment by Innixma** [comment]
Hi @jeonginseo , could you try using pre-release or waiting for v0.1 to release (should be release within 1 week)? We have overhauled a lot of the logic and your issue may have been fixed already.
