### ISSUE TITLE
Running error on Ubuntu 18.04 (DL base AMI)

### ISSUE THREAD

**Issue by zheng-da** [awslabs/autogluon#97]
After I install autogluon from `pip install https://autogluon.s3.amazonaws.com/dist/autogluon-0.0.1-py3-none-any.whl` and import autogluon, I got the following error:

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-9ff6d8eb77d9>", line 1, in <module>
    import autogluon as ag

  File "/usr/local/lib/python3.6/dist-packages/autogluon/__init__.py", line 10, in <module>
    from . import scheduler, searcher, nas, utils

  File "/usr/local/lib/python3.6/dist-packages/autogluon/scheduler/__init__.py", line 5, in <module>
    from .scheduler import *

  File "/usr/local/lib/python3.6/dist-packages/autogluon/scheduler/scheduler.py", line 21, in <module>
    class TaskScheduler(object):

  File "/usr/local/lib/python3.6/dist-packages/autogluon/scheduler/scheduler.py", line 26, in TaskScheduler
    REMOTE_MANAGER = RemoteManager()

  File "/usr/local/lib/python3.6/dist-packages/autogluon/scheduler/remote/remote_manager.py", line 37, in __new__
    cls.start_local_node()

  File "/usr/local/lib/python3.6/dist-packages/autogluon/scheduler/remote/remote_manager.py", line 48, in start_local_node
    remote = Remote.create_local_node(cls.MASTER_IP, port)

  File "/usr/local/lib/python3.6/dist-packages/autogluon/scheduler/remote/remote.py", line 54, in create_local_node
    return cls(ip, port, local=True)

  File "/usr/local/lib/python3.6/dist-packages/autogluon/scheduler/remote/remote.py", line 31, in __init__
    super(Remote, self).__init__(processes=False)

  File "/usr/local/lib/python3.6/dist-packages/distributed/client.py", line 721, in __init__
    self.start(timeout=timeout)

  File "/usr/local/lib/python3.6/dist-packages/distributed/client.py", line 886, in start
    sync(self.loop, self._start, **kwargs)

  File "/usr/local/lib/python3.6/dist-packages/distributed/utils.py", line 333, in sync
    raise exc.with_traceback(tb)

  File "/usr/local/lib/python3.6/dist-packages/distributed/utils.py", line 317, in f
    result[0] = yield future

  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 735, in run
    value = future.result()

  File "/usr/local/lib/python3.6/dist-packages/distributed/client.py", line 952, in _start
    **self._startup_kwargs

  File "/usr/local/lib/python3.6/dist-packages/distributed/deploy/spec.py", line 346, in _
    await self._start()

  File "/usr/local/lib/python3.6/dist-packages/distributed/deploy/spec.py", line 264, in _start
    **self.scheduler_spec.get("options", {})

  File "/usr/local/lib/python3.6/dist-packages/distributed/scheduler.py", line 903, in __init__
    from distributed.dashboard import BokehScheduler

  File "/usr/local/lib/python3.6/dist-packages/distributed/dashboard/__init__.py", line 1, in <module>
    from .scheduler import BokehScheduler

  File "/usr/local/lib/python3.6/dist-packages/distributed/dashboard/scheduler.py", line 402, in <module>
    import pynvml  # noqa: 1708

  File "/usr/local/lib/python3.6/dist-packages/pynvml.py", line 1831
    print c_count.value
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(c_count.value)?
```

**Comment by zhanghang1989** [comment]
fixed.
