### ISSUE TITLE
Fix fit_weighted_ensemble on high_quality preset

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#994]
Following code crashes:

```
from autogluon.tabular import TabularDataset, TabularPredictor
train_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
test_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/test.csv')
predictor = TabularPredictor(label='class').fit(train_data, presets='high_quality_fast_inference_only_refit', time_limit=30, num_bag_folds=2)
leaderboard = predictor.leaderboard(test_data)
predictor.fit_weighted_ensemble()
```

Leaderboard before crash:

```
>>> leaderboard = predictor.leaderboard(test_data)
                           model  score_test  score_val  pred_time_test  pred_time_val   fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0   RandomForestGini_BAG_L2_FULL    0.864981        NaN        3.096247            NaN  12.483953                 0.488807                     NaN           3.357432            2       True         13
1       WeightedEnsemble_L3_FULL    0.864981        NaN        3.121108            NaN  12.500779                 0.024860                0.071648           0.016826            3       True         14
2   RandomForestEntr_BAG_L1_FULL    0.861808        NaN        0.608568            NaN   3.359873                 0.608568                     NaN           3.359873            1       True          9
3       WeightedEnsemble_L2_FULL    0.861501        NaN        1.343803            NaN   7.070148                 0.003723                0.073778           0.497537            2       True         12
4   RandomForestGini_BAG_L1_FULL    0.860477        NaN        0.622837            NaN   2.759001                 0.622837                     NaN           2.759001            1       True          8
5     ExtraTreesGini_BAG_L1_FULL    0.846044        NaN        1.267359            NaN   2.553910                 1.267359                     NaN           2.553910            1       True         10
6     KNeighborsUnif_BAG_L1_FULL    0.773160        NaN        0.108675            NaN   0.453738                 0.108675                     NaN           0.453738            1       True         11
7        RandomForestGini_BAG_L2         NaN   0.860441             NaN       2.715280  14.370307                      NaN                0.625697           3.923823            2      False          6
8            WeightedEnsemble_L3         NaN   0.860441             NaN       2.787274  14.387079                      NaN                0.071994           0.016772            3      False          7
9            WeightedEnsemble_L2         NaN   0.855911             NaN       1.539686  13.742303                      NaN                0.073748           6.212242            2      False          5
10       RandomForestGini_BAG_L1         NaN   0.855450             NaN       0.625235   3.415056                      NaN                0.625235           3.415056            1      False          1
11       RandomForestEntr_BAG_L1         NaN   0.854733             NaN       0.624586   3.925570                      NaN                0.624586           3.925570            1      False          2
12         ExtraTreesGini_BAG_L1         NaN   0.842884             NaN       0.623644   2.916423                      NaN                0.623644           2.916423            1      False          3
13         KNeighborsUnif_BAG_L1         NaN   0.772272             NaN       0.216118   0.189436                      NaN                0.216118           0.189436            1      False          4
```

Error:

```
>>> predictor.fit_weighted_ensemble()
Fitting model: WeightedEnsemble_L3Best ...
	0.8609	 = Validation accuracy score
	7.72s	 = Training runtime
	0.07s	 = Validation runtime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/remote/autogluon/tabular/src/autogluon/tabular/predictor/predictor.py", line 1586, in fit_weighted_ensemble
    models += trainer.generate_weighted_ensemble(X=X_stack_preds, y=y, level=weighted_ensemble_level, stack_name=stack_name, base_model_names=base_models, name_suffix=name_suffix, time_limit=time_limit)
  File "/home/ubuntu/remote/autogluon/tabular/src/autogluon/tabular/trainer/abstract_trainer.py", line 870, in generate_weighted_ensemble
    if cur_score > best_score:
TypeError: '>' not supported between instances of 'float' and 'NoneType'
```
This occurs because the best model `WeightedEnsemble_L3_FULL` has None as its validation score, so when comparing with `WeightedEnsemble_L3Best`, the type error occurs.

**Comment by ooghry** [comment]
Hello
I ran autogluon with `presets='good_quality_faster_inference_only_refit'`, Is it normal to have NaN values in score_test and score_val?(I'm very new to ML)
  | model | score_test | score_val | pred_time_test | pred_time_val | fit_time | pred_time_test_marginal | pred_time_val_marginal | fit_time_marginal | stack_level | can_infer | fit_order
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ExtraTreesEntr_BAG_L1_FULL | 0.608696 | 0.540839 | 0.132715 | 0.179417 | 1.165962 | 0.132715 | 0.179417 | 1.165962 | 1 | True | 31
LightGBMLarge_BAG_L2_FULL | 0.577640 | NaN | 1.054579 | NaN | 31.177773 | 0.025090 | NaN | 5.023543 | 2 | True | 47
CatBoost_BAG_L2_FULL | 0.577640 | NaN | 1.060760 | NaN | 29.185821 | 0.031271 | NaN | 3.031591 | 2 | True | 41
LightGBMXT_BAG_L1_FULL | 0.571429 | NaN | 0.010864 | NaN | 0.794972 | 0.010864 | NaN | 0.794972 | 1 | True | 25
LightGBMLarge_BAG_L1_FULL | 0.571429 | NaN | 0.017364 | NaN | 4.672307 | 0.017364 | NaN | 4.672307 | 1 | True | 35
CatBoost_BAG_L1_FULL | 0.571429 | NaN | 0.022594 | NaN | 3.187270 | 0.022594 | NaN | 3.187270 | 1 | True | 29
LightGBM_BAG_L2_FULL | 0.571429 | NaN | 1.046572 | NaN | 27.998680 | 0.017083 | NaN | 1.844450 | 2 | True | 38
RandomForestEntr_BAG_L2_FULL | 0.571429 | 0.570640 | 1.161432 | NaN | 30.411467 | 0.131943 | 0.174610 | 4.257237 | 2 | True | 40
RandomForestGini_BAG_L1_FULL | 0.565217 | 0.562914 | 0.144291 | 0.172612 | 2.452318 | 0.144291 | 0.172612 | 2.452318 | 1 | True | 27
ExtraTreesEntr_BAG_L2_FULL | 0.565217 | 0.583885 | 1.166744 | NaN | 27.296622 | 0.137255 | 0.180288 | 1.142392 | 2 | True | 43
LightGBMXT_BAG_L2_FULL | 0.559006 | NaN | 1.044361 | NaN | 26.933498 | 0.014872 | NaN | 0.779269 | 2 | True | 37
ExtraTreesGini_BAG_L2_FULL | 0.559006 | 0.570640 | 1.169785 | NaN | 27.223158 | 0.140296 | 0.188561 | 1.068928 | 2 | True | 42
WeightedEnsemble_L2_FULL | 0.546584 | NaN | 0.158720 | NaN | 6.289927 | 0.004215 | 0.002277 | 0.000914 | 2 | True | 36
ExtraTreesGini_BAG_L1_FULL | 0.540373 | 0.536424 | 0.134287 | 0.175392 | 1.043732 | 0.134287 | 0.175392 | 1.043732 | 1 | True | 30
XGBoost_BAG_L2_FULL | 0.540373 | NaN | 1.067397 | NaN | 33.706256 | 0.037908 | NaN | 7.552027 | 2 | True | 45
RandomForestEntr_BAG_L1_FULL | 0.534161 | 0.586093 | 0.128067 | 0.187858 | 4.377166 | 0.128067 | 0.187858 | 4.377166 | 1 | True | 28
NeuralNetMXNet_BAG_L2_FULL | 0.534161 | NaN | 1.321472 | NaN | 28.029497 | 0.291983 | NaN | 1.875267 | 2 | True | 46
LightGBM_BAG_L1_FULL | 0.527950 | NaN | 0.010002 | NaN | 1.340238 | 0.010002 | NaN | 1.340238 | 1 | True | 26
XGBoost_BAG_L1_FULL | 0.527950 | NaN | 0.022682 | NaN | 4.114461 | 0.022682 | NaN | 4.114461 | 1 | True | 33
NeuralNetFastAI_BAG_L1_FULL | 0.515528 | NaN | 0.120959 | NaN | 1.379579 | 0.120959 | NaN | 1.379579 | 1 | True | 32
RandomForestGini_BAG_L2_FULL | 0.509317 | 0.572848 | 1.164898 | NaN | 28.503777 | 0.135409 | 0.172570 | 2.349547 | 2 | True | 39
NeuralNetFastAI_BAG_L2_FULL | 0.503106 | NaN | 1.176534 | NaN | 28.076050 | 0.147045 | NaN | 1.921820 | 2 | True | 44
WeightedEnsemble_L3_FULL | 0.503106 | NaN | 1.179522 | NaN | 28.076547 | 0.002989 | 0.002829 | 0.000497 | 3 | True | 48
NeuralNetMXNet_BAG_L1_FULL | 0.496894 | NaN | 0.285664 | NaN | 1.626225 | 0.285664 | NaN | 1.626225 | 1 | True | 34
NeuralNetFastAI_BAG_L2 | NaN | 0.700883 | NaN | 98.260615 | 10408.365874 | NaN | 23.396660 | 464.414229 | 2 | False | 20
WeightedEnsemble_L3 | NaN | 0.700883 | NaN | 98.262814 | 10409.057123 | NaN | 0.002199 | 0.691249 | 3 | False | 24
WeightedEnsemble_L2 | NaN | 0.629139 | NaN | 23.672068 | 2696.058871 | NaN | 0.002158 | 0.691019 | 2 | False | 12
LightGBMXT_BAG_L1 | NaN | 0.618102 | NaN | 1.023088 | 363.510963 | NaN | 1.023088 | 363.510963 | 1 | False | 1
CatBoost_BAG_L2 | NaN | 0.615894 | NaN | 78.011608 | 13056.249446 | NaN | 3.147652 | 3112.297801 | 2 | False | 17
CatBoost_BAG_L1 | NaN | 0.612583 | NaN | 3.061184 | 3019.257595 | NaN | 3.061184 | 3019.257595 | 1 | False | 5
XGBoost_BAG_L2 | NaN | 0.612583 | NaN | 76.179989 | 11992.490612 | NaN | 1.316033 | 2048.538967 | 2 | False | 21
NeuralNetMXNet_BAG_L2 | NaN | 0.612583 | NaN | 120.161211 | 10962.626437 | NaN | 45.297256 | 1018.674792 | 2 | False | 22
LightGBM_BAG_L2 | NaN | 0.609272 | NaN | 75.906800 | 10761.273764 | NaN | 1.042845 | 817.322119 | 2 | False | 14
LightGBMLarge_BAG_L1 | NaN | 0.605960 | NaN | 1.062640 | 2646.004543 | NaN | 1.062640 | 2646.004543 | 1 | False | 11
XGBoost_BAG_L1 | NaN | 0.605960 | NaN | 1.271662 | 1898.832552 | NaN | 1.271662 | 1898.832552 | 1 | False | 9
LightGBMXT_BAG_L2 | NaN | 0.605960 | NaN | 75.891016 | 10311.905414 | NaN | 1.027061 | 367.953769 | 2 | False | 13
NeuralNetFastAI_BAG_L1 | NaN | 0.587196 | NaN | 21.375160 | 433.024337 | NaN | 21.375160 | 433.024337 | 1 | False | 8
RandomForestEntr_BAG_L1 | NaN | 0.586093 | NaN | 0.184090 | 4.235463 | NaN | 0.184090 | 4.235463 | 1 | False | 4
LightGBM_BAG_L1 | NaN | 0.584989 | NaN | 1.044137 | 725.853619 | NaN | 1.044137 | 725.853619 | 1 | False | 2
ExtraTreesEntr_BAG_L2 | NaN | 0.583885 | NaN | 75.086402 | 9945.115346 | NaN | 0.222446 | 1.163702 | 2 | False | 19
LightGBMLarge_BAG_L2 | NaN | 0.581678 | NaN | 75.973866 | 12763.713071 | NaN | 1.109910 | 2819.761426 | 2 | False | 23
RandomForestGini_BAG_L2 | NaN | 0.572848 | NaN | 75.056527 | 9946.418140 | NaN | 0.192572 | 2.466495 | 2 | False | 15
RandomForestEntr_BAG_L2 | NaN | 0.570640 | NaN | 75.044941 | 9948.213258 | NaN | 0.180986 | 4.261613 | 2 | False | 16
ExtraTreesGini_BAG_L2 | NaN | 0.570640 | NaN | 75.061571 | 9945.007675 | NaN | 0.197615 | 1.056031 | 2 | False | 18
NeuralNetMXNet_BAG_L1 | NaN | 0.567329 | NaN | 45.286977 | 848.709200 | NaN | 45.286977 | 848.709200 | 1 | False | 10
RandomForestGini_BAG_L1 | NaN | 0.562914 | NaN | 0.193807 | 2.447076 | NaN | 0.193807 | 2.447076 | 1 | False | 3
ExtraTreesEntr_BAG_L1 | NaN | 0.540839 | NaN | 0.174906 | 1.023433 | NaN | 0.174906 | 1.023433 | 1 | False | 7
ExtraTreesGini_BAG_L1 | NaN | 0.536424 | NaN | 0.186304 | 1.052864 | NaN | 0.186304 | 1.052864 | 1 | False | 6

**Comment by Innixma** [comment]
@ooghry This is normal: You specified a preset with `only_refit`. This is a complex option that avoids saving the bags to disk as an optimization step and only saves the `_FULL` models (10-100x disk space usage reduction). Because of this, the BAG models cannot predict on new data as they don't exist (refer to `can_infer` column). Further, `_FULL` models are trained on 100% of the data, so they can't produce validation scores (Random Forest / KNN have special implementations that allow them to compute val scores regardless).

You may wish to use `best_quality` preset to start with and then use the other presets if `best_quality` is too intensive for your needs. You can also call `predictor.refit_full('all')` after training `best_quality` to get a leaderboard where all models can compute test scores.
